-- ProsperApp schema reference for Codex agents.
-- Purpose:
--   This file is a read-only reference for agents that need table/column/RPC information.
--   Do not execute this file as a migration. Execute the dedicated files instead:
--     - Sql/store_order_accounting_tables.sql
--     - Sql/store_settings_functions.sql
--     - Sql/store_rpc/01_business_day.sql
--     - Sql/store_rpc/02_store_masters.sql
--     - Sql/store_rpc/03_slips.sql
--     - Sql/store_rpc/04_orders.sql
--     - Sql/store_rpc/05_checkout.sql
--     - Sql/store_rpc/06_receipts.sql
--     - Sql/store_rpc/99_grants.sql
--     - Sql/quick_entry_account_master_updates.sql
--   Sql/store_rpc_functions.sql is a non-executable index for the split RPC files.
--
-- Current DB access policy:
--   Application DB operations should go through Supabase RPC functions.
--   Tables have RLS enabled where added by this project; policies are intentionally not defined here.

-- -----------------------------------------------------------------------------
-- Existing master / receipt / journal tables provided by Supabase schema snapshot
-- -----------------------------------------------------------------------------

-- account_master
--   account_code text
--   account_name text
--   category text
--   dc_type text
--   requires_subaccount boolean
--   is_active boolean
--   sort_order integer

-- account_subaccount_map
--   company_id bigint
--   account_code text
--   subaccount_id bigint
--   is_default boolean
--   sort_order integer
--   created_at timestamp with time zone

-- company_master
--   company_id bigint
--   company_code text
--   company_name text
--   is_active boolean
--   created_at timestamp with time zone
--   company_short_code text

-- department_master
--   department_id bigint
--   company_id bigint
--   department_code text
--   department_name text
--   is_active boolean

-- document_file_no_sequences
--   company_id bigint
--   seq_date date
--   last_no integer

-- document_files
--   file_id bigint
--   company_id bigint
--   file_no text
--   file_name text
--   original_file_name text
--   file_ext text
--   storage_path text
--   file_hash text
--   uploaded_at timestamp with time zone
--   uploaded_by text
--   drive_file_id text
--   drive_url text

-- documents
--   document_id bigint
--   company_id bigint
--   file_id bigint
--   document_type text
--   document_date date
--   amount numeric
--   counterparty text
--   title text
--   memo text
--   status text
--   created_at timestamp with time zone
--   updated_at timestamp with time zone
--   upload_source_id bigint
--   department_id bigint

-- document_journal_links
--   link_id bigint
--   document_id bigint
--   journal_entry_id bigint
--   relation_type text
--   created_at timestamp with time zone

-- journal_entries
--   journal_entry_id bigint
--   company_id bigint
--   entry_date date
--   slip_no text
--   description text
--   created_at timestamp with time zone
--   created_by text
--   approved_at timestamp with time zone
--   approved_by text

-- journal_entry_lines
--   line_id bigint
--   journal_entry_id bigint
--   line_no integer
--   account_code text
--   subaccount_id bigint
--   dc_flag text
--   amount numeric
--   tax_code text
--   line_memo text
--   account_name_snapshot text
--   subaccount_name_snapshot text
--   created_at timestamp with time zone

-- subaccount_master
--   subaccount_id bigint
--   company_id bigint
--   subaccount_code text
--   subaccount_name text
--   subaccount_type text
--   is_active boolean
--   sort_order integer
--   created_at timestamp with time zone
--   updated_at timestamp with time zone

-- upload_source_master
--   upload_source_id bigint
--   company_id bigint
--   upload_source_code text
--   upload_source_name text
--   source_type text
--   default_department_id bigint
--   default_offset_account_code text
--   default_offset_subaccount_id bigint
--   drive_source_folder_id text
--   is_active boolean

-- -----------------------------------------------------------------------------
-- Store operation tables created by Sql/store_order_accounting_tables.sql
-- -----------------------------------------------------------------------------

-- store_table_master: store-specific table/seat master.
create table if not exists public.store_table_master (
    table_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    table_code text not null,
    table_name text,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_table_master_code unique (company_id, department_id, table_code)
);

-- cast_master: cast display names and store affiliation. Do not put high-risk HR data here.
create table if not exists public.cast_master (
    cast_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_code text,
    display_name text not null,
    joined_on date not null default ((now() at time zone 'Asia/Tokyo')::date),
    status text not null default 'active', -- active / inactive / left
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_cast_master_status check (status in ('active', 'inactive', 'left')),
    constraint uq_cast_master_code unique (company_id, department_id, cast_code)
);

-- store_item_category_master: order item category master.
create table if not exists public.store_item_category_master (
    item_category_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    category_code text not null,
    category_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_item_category_master_code unique (company_id, department_id, category_code)
);

-- store_item_master: order item master. Prices are tax-included integer yen.
create table if not exists public.store_item_master (
    item_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    item_category_id bigint references public.store_item_category_master(item_category_id),
    item_name text not null,
    default_price numeric(12, 0) not null default 0,
    is_cast_back_target boolean not null default false,
    cast_back_unit_amount numeric(12, 0) not null default 0,
    cast_back_regular_unit_amount numeric(12, 0) not null default 0,
    cast_back_nomination_unit_amount numeric(12, 0) not null default 0,
    cast_back_type text not null default 'drink', -- drink / sales / other
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_item_master_default_price check (default_price >= 0),
    constraint chk_store_item_master_cast_back_unit_amount check (cast_back_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_regular_unit_amount check (cast_back_regular_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_nomination_unit_amount check (cast_back_nomination_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_type check (cast_back_type in ('drink', 'sales', 'other')),
    constraint uq_store_item_master_name unique (company_id, department_id, item_name)
);

-- payment_method_master: checkout payment method master.
create table if not exists public.payment_method_master (
    payment_method_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_code text not null,
    payment_method_name text not null,
    requires_received_amount boolean not null default false,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_payment_method_master_code unique (company_id, department_id, payment_method_code)
);

-- store_business_days: store business day opened/closed by opening and closing flows.
create table if not exists public.store_business_days (
    business_day_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_date date not null,
    opened_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    status text not null default 'open', -- open / closed / cancelled
    opened_by text,
    closed_by text,
    memo text,
    drink_delivery_amount numeric(12, 0) not null default 0,
    drink_delivery_amount_entered boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_business_days_status check (status in ('open', 'closed', 'cancelled')),
    constraint chk_store_business_days_drink_delivery_amount check (drink_delivery_amount >= 0),
    constraint chk_store_business_days_closed_at check (closed_at is null or closed_at >= opened_at)
);

-- store_cast_attendance: per-business-day cast attendance.
-- Opening saves selected casts here with clock_in_at as checked_in.
create table if not exists public.store_cast_attendance (
    attendance_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint not null references public.store_business_days(business_day_id) on delete cascade,
    business_date date not null,
    cast_id bigint not null references public.cast_master(cast_id),
    attendance_status text not null default 'scheduled', -- scheduled / checked_in / checked_out / absent / cancelled
    clock_in_at timestamp with time zone,
    clock_out_at timestamp with time zone,
    uses_send_service boolean not null default false,
    source text not null default 'opening', -- opening / manual / import
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_cast_attendance_status check (attendance_status in ('scheduled', 'checked_in', 'checked_out', 'absent', 'cancelled')),
    constraint chk_store_cast_attendance_source check (source in ('opening', 'manual', 'import')),
    constraint chk_store_cast_attendance_clock_out check (clock_out_at is null or clock_in_at is null or clock_out_at >= clock_in_at),
    constraint uq_store_cast_attendance_day_cast unique (business_day_id, cast_id)
);

-- store_slips: one slip per table/session. Business day is set by current open business day.
create table if not exists public.store_slips (
    slip_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    table_id bigint references public.store_table_master(table_id),
    slip_no text,
    opened_at timestamp with time zone not null,
    closed_at timestamp with time zone,
    status text not null default 'open', -- open / checked_out / cancelled
    customer_count integer not null default 0,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slips_status check (status in ('open', 'checked_out', 'cancelled')),
    constraint chk_store_slips_customer_count check (customer_count >= 0),
    constraint chk_store_slips_closed_at check (closed_at is null or closed_at >= opened_at),
    constraint uq_store_slips_slip_no unique (company_id, department_id, slip_no)
);

-- store_slip_customers: customer rows inside a slip. Row count is customer count.
create table if not exists public.store_slip_customers (
    slip_customer_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    customer_label text,
    entered_at timestamp with time zone not null,
    left_at timestamp with time zone,
    status text not null default 'active', -- active / left / cancelled
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_customers_status check (status in ('active', 'left', 'cancelled')),
    constraint chk_store_slip_customers_left_at check (left_at is null or left_at >= entered_at),
    constraint uq_store_slip_customers_line unique (slip_id, line_no)
);

-- store_slip_casts: nominated casts on a slip.
create table if not exists public.store_slip_casts (
    slip_cast_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    nomination_type text not null default 'nomination', -- nomination / in_store / companion / help / other
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    status text not null default 'active', -- active / ended / cancelled
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_casts_nomination_type check (nomination_type in ('nomination', 'in_store', 'companion', 'help', 'other')),
    constraint chk_store_slip_casts_status check (status in ('active', 'ended', 'cancelled')),
    constraint chk_store_slip_casts_ended_at check (started_at is null or ended_at is null or ended_at >= started_at)
);

-- store_order_lines: order lines on a slip. Amounts are tax-included integer yen.
create table if not exists public.store_order_lines (
    order_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    item_id bigint references public.store_item_master(item_id) on delete set null,
    item_name_snapshot text not null,
    quantity numeric(10, 2) not null default 1,
    unit_price numeric(12, 0) not null default 0,
    amount numeric(12, 0) not null default 0,
    ordered_at timestamp with time zone not null default now(),
    status text not null default 'active', -- active / voided
    voided_at timestamp with time zone,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_lines_quantity check (quantity > 0),
    constraint chk_store_order_lines_unit_price check (unit_price >= 0),
    constraint chk_store_order_lines_amount check (amount >= 0),
    constraint chk_store_order_lines_status check (status in ('active', 'voided')),
    constraint uq_store_order_lines_line unique (slip_id, line_no)
);

-- store_order_line_cast_backs: cast-specific back amounts generated from order lines.
create table if not exists public.store_order_line_cast_backs (
    order_line_cast_back_id bigint generated by default as identity primary key,
    order_line_id bigint not null references public.store_order_lines(order_line_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    back_type text not null default 'drink', -- drink / sales / other
    quantity numeric(10, 2) not null default 1,
    back_unit_amount numeric(12, 0) not null default 0,
    back_amount numeric(12, 0) not null default 0,
    status text not null default 'active', -- active / voided / cancelled
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_line_cast_backs_type check (back_type in ('drink', 'sales', 'other')),
    constraint chk_store_order_line_cast_backs_quantity check (quantity > 0),
    constraint chk_store_order_line_cast_backs_unit_amount check (back_unit_amount >= 0),
    constraint chk_store_order_line_cast_backs_amount check (back_amount >= 0),
    constraint chk_store_order_line_cast_backs_status check (status in ('active', 'voided', 'cancelled'))
);

-- store_checkouts: one checkout per slip. Amounts are snapshots at checkout time.
create table if not exists public.store_checkouts (
    checkout_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    checkout_at timestamp with time zone not null,
    subtotal_amount numeric(12, 0) not null default 0,
    service_tax_amount numeric(12, 0) not null default 0,
    total_amount numeric(12, 0) not null default 0,
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    received_amount numeric(12, 0),
    change_amount numeric(12, 0),
    status text not null default 'draft', -- draft / confirmed / cancelled
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_checkouts_slip unique (slip_id),
    constraint chk_store_checkouts_total_amount check (total_amount >= 0),
    constraint chk_store_checkouts_received_amount check (received_amount is null or received_amount >= 0),
    constraint chk_store_checkouts_change_amount check (change_amount is null or change_amount >= 0),
    constraint chk_store_checkouts_status check (status in ('draft', 'confirmed', 'cancelled'))
);

-- store_checkout_payments: split payment rows for a checkout.
create table if not exists public.store_checkout_payments (
    checkout_payment_id bigint generated by default as identity primary key,
    checkout_id bigint not null references public.store_checkouts(checkout_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    payment_method_code text not null,
    payment_method_name text not null,
    amount numeric(12, 0) not null default 0,
    status text not null default 'confirmed', -- confirmed / cancelled
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_checkout_payments_amount check (amount >= 0),
    constraint chk_store_checkout_payments_status check (status in ('confirmed', 'cancelled'))
);

-- store_slip_cast_sales_adjustments: closing-time sales amount allocation by slip nomination.
create table if not exists public.store_slip_cast_sales_adjustments (
    adjustment_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    checkout_id bigint not null references public.store_checkouts(checkout_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    slip_cast_id bigint not null references public.store_slip_casts(slip_cast_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    source_amount_type text not null default 'total', -- subtotal / total
    split_mode text not null default 'split', -- split / full
    base_amount numeric(12, 0) not null default 0,
    sales_amount numeric(12, 0) not null default 0,
    status text not null default 'confirmed', -- confirmed / cancelled
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_slip_cast_sales_adjustments_slip_cast unique (slip_id, slip_cast_id),
    constraint chk_store_slip_cast_sales_adjustments_source check (source_amount_type in ('subtotal', 'total')),
    constraint chk_store_slip_cast_sales_adjustments_split check (split_mode in ('split', 'full')),
    constraint chk_store_slip_cast_sales_adjustments_base_amount check (base_amount >= 0),
    constraint chk_store_slip_cast_sales_adjustments_sales_amount check (sales_amount >= 0),
    constraint chk_store_slip_cast_sales_adjustments_status check (status in ('confirmed', 'cancelled'))
);

-- Important indexes from the executable migration:
--   ux_store_business_days_one_open: unique (company_id, department_id) where status = 'open'
--   idx_store_business_days_lookup: (company_id, department_id, business_date, status)
--   idx_store_cast_attendance_day_status: (company_id, department_id, business_day_id, attendance_status)
--   idx_store_cast_attendance_cast: (cast_id, business_date)
--   idx_store_slips_open: (company_id, department_id, status, opened_at)
--   idx_store_slips_business_day: (business_day_id, status)
--   idx_store_slip_customers_slip_status: (slip_id, status)
--   idx_store_order_lines_slip_status: (slip_id, status)
--   idx_store_order_line_cast_backs_cast_date: (company_id, department_id, cast_id, business_date, status)
--   idx_store_order_line_cast_backs_line: (order_line_id, status)
--   idx_store_checkouts_date: (company_id, department_id, checkout_at)
--   idx_store_checkout_payments_checkout: (checkout_id, status)
--   idx_store_slip_cast_sales_adjustments_day: (company_id, department_id, business_day_id, status)
--   idx_store_slip_cast_sales_adjustments_slip: (slip_id, status)
--   idx_store_slip_cast_sales_adjustments_cast_date: (company_id, department_id, cast_id, business_date, status)

-- -----------------------------------------------------------------------------
-- RPC functions used by the application
-- -----------------------------------------------------------------------------

-- Store settings:
--   get_store_departments()
--     returns department_id, company_id, department_code, department_name, is_active

-- Store context and business day:
--   get_store_context(p_department_id bigint)
--     returns company_id, department_id, department_name
--   get_current_business_day(p_department_id bigint)
--     returns business_day_id, company_id, department_id, business_date, opened_at, closed_at, status, memo
--   open_business_day(p_department_id bigint, p_business_date date, p_memo text)
--     returns business_day_id, company_id, department_id, business_date, opened_at, closed_at, status, memo
--   open_business_day_with_attendance(p_department_id bigint, p_business_date date, p_attending_cast_ids bigint[], p_memo text)
--     returns business_day_id, company_id, department_id, business_date, opened_at, closed_at, status, memo
--     legacy overload; saves selected active same-company casts to store_cast_attendance as scheduled.
--   open_business_day_with_attendance(p_department_id bigint, p_business_date date, p_attendance_entries jsonb, p_memo text)
--     returns business_day_id, company_id, department_id, business_date, opened_at, closed_at, status, memo
--     p_attendance_entries supports { cast_id, clock_in_time } and saves checked_in rows with clock_in_at.
--   add_business_day_attendance(p_department_id bigint, p_business_day_id bigint, p_attendance_entries jsonb)
--     returns business_day_id, company_id, department_id, business_date, opened_at, closed_at, status, memo
--     adds checked_in attendance rows after the business day has already opened.
--   get_open_slip_count(p_department_id bigint, p_business_day_id bigint)
--     returns integer
--   get_business_day_drink_delivery_amount(p_department_id bigint, p_business_day_id bigint)
--     returns numeric. Closing drink-cost entry uses this as the current business-day delivery amount.
--   get_business_day_drink_delivery_status(p_department_id bigint, p_business_day_id bigint)
--     returns drink_delivery_amount and is_entered so 0 yen can be distinguished from not entered.
--   save_business_day_drink_delivery_amount(p_department_id bigint, p_business_day_id bigint, p_drink_delivery_amount numeric)
--     updates store_business_days.drink_delivery_amount and marks drink_delivery_amount_entered for the open business day.
--   get_business_day_closing_attendance(p_department_id bigint, p_business_day_id bigint)
--     returns attendance_id, cast_id, cast_display_name, cast_department_name, attendance_status,
--       clock_in_at, clock_out_at, uses_send_service for closing attendance input.
--   save_business_day_closing_attendance(p_department_id bigint, p_business_day_id bigint, p_attendance_entries jsonb)
--     updates registered attendance rows with { attendance_id, clock_in_time, clock_out_time, uses_send_service }.
--   get_business_day_cast_sales_adjustment_status(p_department_id bigint, p_business_day_id bigint)
--     returns required_slip_count, completed_slip_count, missing_slip_count.
--   get_cast_sales_adjustment_slips(p_department_id bigint, p_business_day_id bigint)
--     returns checked-out slips with active nominated casts, cast_names, and their saved adjustment status.
--   get_cast_sales_adjustment_detail(p_department_id bigint, p_slip_id bigint)
--     returns checkout snapshot and nominated cast rows for one checked-out slip.
--   save_cast_sales_adjustment(p_department_id bigint, p_slip_id bigint, p_adjustments jsonb, p_source_amount_type text, p_split_mode text)
--     replaces the per-slip adjustment rows for all active nominated casts.
--   close_business_day(p_department_id bigint, p_business_day_id bigint, p_memo text, p_pending_receipt_status text default 'unprocessed')
--     returns business_day_id, company_id, department_id, business_date, opened_at, closed_at, status, memo.
--     rejects closing when open slips, missing drink delivery input, no attendance,
--     missing clock-out, or missing cast sales adjustment remain.
--     Pending receipt documents are UI warnings, not close blockers.

-- Slip creation and listing:
--   get_store_tables(p_department_id bigint)
--     returns table_id, table_code, table_name
--   get_store_casts(p_department_id bigint)
--     returns cast_id, cast_code, display_name, department_name
--     includes active casts from all active departments in the same company, for help/temporary assignments.
--   get_store_cast_admin_list(p_department_id bigint)
--     returns cast_id, display_name, joined_on for casts belonging to the current store.
--   create_store_cast(p_department_id bigint, p_display_name text)
--     creates an active cast for the current store. joined_on is set to the current Asia/Tokyo date.
--   get_business_day_slips(p_department_id bigint, p_business_day_id bigint)
--     returns slip_id, slip_no, table_id, table_code, table_name, opened_at, status,
--       customer_count, customer_names, cast_names, accounting_amount, memo
--   get_order_entry_slips(p_department_id bigint, p_business_day_id bigint)
--     returns slip_id, table_id, table_code, table_name, opened_at, customer_count, memo
--   get_store_order_items(p_department_id bigint)
--     returns item_id, item_name, default_price, category_code, category_name,
--       is_cast_back_target, cast_back_regular_unit_amount, cast_back_nomination_unit_amount, cast_back_type
--   get_store_item_admin_catalog(p_department_id bigint)
--     returns category and item rows for Opening/Items management.
--   upsert_store_item_category(p_department_id, p_item_category_id, p_category_code, p_category_name, p_sort_order, p_is_active)
--     inserts/updates store_item_category_master for the current store.
--   upsert_store_item(p_department_id, p_item_id, p_item_category_id, p_item_name, p_default_price,
--       p_is_active, p_is_cast_back_target, p_cast_back_regular_unit_amount,
--       p_cast_back_nomination_unit_amount, p_cast_back_type)
--     inserts/updates store_item_master. v1 UI saves cast back type as drink.
--   delete_store_item(p_department_id bigint, p_item_id bigint)
--     deletes a store item master row. Existing order rows keep item_name_snapshot/unit_price/amount and clear item_id.
--   get_order_attending_casts(p_department_id bigint, p_business_day_id bigint)
--     returns cast_id, display_name, department_name
--     display_name is the cast name; UI composes display_name:department_name when needed.
--   add_store_order_lines(p_department_id bigint, p_slip_id bigint, p_order_lines jsonb)
--     returns inserted_count
--     p_order_lines supports { item_id, quantity, cast_back_cast_id }.
--     Back target items require cast_back_cast_id and create store_order_line_cast_backs rows.
--   get_store_slip_detail(p_department_id bigint, p_slip_id bigint)
--     returns flattened slip, customer, nomination, and order rows for Slips/Edit.
--   add_store_slip_customers(p_department_id bigint, p_slip_id bigint, p_customer_labels text[], p_entered_at timestamptz)
--     adds active customer rows to an open slip with the selected entered_at and refreshes store_slips.customer_count.
--   add_store_slip_nominations(p_department_id bigint, p_slip_id bigint, p_cast_nominations jsonb)
--     adds nomination rows to an open slip. p_cast_nominations uses { cast_id, nomination_type, companion_time }.
--   leave_store_slip_customer(p_department_id bigint, p_slip_customer_id bigint, p_left_at timestamptz)
--     marks an active customer row left and refreshes store_slips.customer_count.
--   void_store_order_line(p_department_id bigint, p_order_line_id bigint)
--     marks an active order line and related store_order_line_cast_backs rows voided.
--   confirm_store_checkout(p_department_id bigint, p_slip_id bigint, p_closed_at timestamptz, p_payments jsonb, p_received_amount numeric)
--     confirms checkout, stores subtotal/service tax/total snapshots, split payment rows, closes active customers, and marks the slip checked_out.
--     p_payments supports { method_code, amount } with method_code in cash/cat/paypay.
--   create_store_slip(
--       p_department_id bigint,
--       p_table_id bigint,
--       p_opened_at timestamp with time zone,
--       p_customer_labels text[],
--       p_cast_nominations jsonb,
--       p_memo text
--     )
--     returns slip_id

-- Receipt quick entry:
--   get_pending_receipts(p_department_id bigint, p_status text default 'unprocessed')
--     returns document_id, file_id, document_date, amount, status, file_name, drive_file_id, drive_url, storage_path
--   quick_enter_receipt(
--       p_department_id bigint,
--       p_document_id text,
--       p_payment_date date,
--       p_amount numeric,
--       p_account_subject text,
--       p_description text,
--       p_group_code text,
--       p_status text default 'quick_entered'
--     )
--     returns document_id
--   mark_receipt_scan_mistake(p_department_id bigint, p_document_id text, p_status text default 'excluded')
--     returns document_id

-- All RPC functions above are expected to be:
--   language sql/plpgsql
--   security definer
--   set search_path = public
--   grant execute to anon/authenticated/service_role for non-sensitive read functions,
--   and to authenticated/service_role only for sensitive or mutating functions.

-- -----------------------------------------------------------------------------
-- Quick-entry account master updates
-- -----------------------------------------------------------------------------

-- Sql/quick_entry_account_master_updates.sql adjusts account/subaccount master data
-- for receipt quick-entry UI choices. The intended active expense subjects include:
--   前渡金, 給料手当, 外注費, 水道光熱費, 通信費, リース費, 衛生費,
--   広告宣伝費, 仕入高, 消耗品費, 保険料, 旅費交通費, 地代家賃,
--   租税公課, 福利厚生費, 会議費, 接待交際費, 雑費.
-- The executable SQL file is currently the source of truth for account_code and
-- subaccount_code inserts/updates.
