begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.store_table_master (
    table_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    table_code text not null,
    table_name text,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_table_master_code unique (company_id, department_id, table_code)
);

create table if not exists public.cast_master (
    cast_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_code text,
    display_name text not null,
    status text not null default 'active',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_cast_master_status check (status in ('active', 'inactive', 'left')),
    constraint uq_cast_master_code unique (company_id, department_id, cast_code)
);

create table if not exists public.store_item_category_master (
    item_category_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    category_code text not null,
    category_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_item_category_master_code unique (company_id, department_id, category_code)
);

create table if not exists public.store_item_master (
    item_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    item_category_id bigint references public.store_item_category_master(item_category_id),
    item_code text not null,
    item_name text not null,
    default_price numeric(12, 0) not null default 0,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_item_master_default_price check (default_price >= 0),
    constraint uq_store_item_master_code unique (company_id, department_id, item_code)
);

create table if not exists public.payment_method_master (
    payment_method_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_code text not null,
    payment_method_name text not null,
    requires_received_amount boolean not null default false,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_payment_method_master_code unique (company_id, department_id, payment_method_code)
);

create table if not exists public.store_business_days (
    business_day_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_date date not null,
    opened_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    status text not null default 'open',
    opened_by text,
    closed_by text,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_business_days_status check (status in ('open', 'closed', 'cancelled')),
    constraint chk_store_business_days_closed_at check (closed_at is null or closed_at >= opened_at)
);

create table if not exists public.store_slips (
    slip_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    table_id bigint references public.store_table_master(table_id),
    slip_no text,
    opened_at timestamp with time zone not null,
    closed_at timestamp with time zone,
    status text not null default 'open',
    customer_count integer not null default 0,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slips_status check (status in ('open', 'checked_out', 'cancelled')),
    constraint chk_store_slips_customer_count check (customer_count >= 0),
    constraint chk_store_slips_closed_at check (closed_at is null or closed_at >= opened_at),
    constraint uq_store_slips_slip_no unique (company_id, department_id, slip_no)
);

alter table public.store_slips
    add column if not exists business_day_id bigint references public.store_business_days(business_day_id);

alter table public.store_slips
    add column if not exists business_date date;

create table if not exists public.store_slip_customers (
    slip_customer_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    customer_label text,
    entered_at timestamp with time zone not null,
    left_at timestamp with time zone,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_customers_status check (status in ('active', 'left', 'cancelled')),
    constraint chk_store_slip_customers_left_at check (left_at is null or left_at >= entered_at),
    constraint uq_store_slip_customers_line unique (slip_id, line_no)
);

create table if not exists public.store_slip_casts (
    slip_cast_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    nomination_type text not null default 'nomination',
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_casts_nomination_type check (nomination_type in ('nomination', 'in_store', 'companion', 'help', 'other')),
    constraint chk_store_slip_casts_status check (status in ('active', 'ended', 'cancelled')),
    constraint chk_store_slip_casts_ended_at check (started_at is null or ended_at is null or ended_at >= started_at)
);

create table if not exists public.store_order_lines (
    order_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    item_id bigint references public.store_item_master(item_id),
    item_name_snapshot text not null,
    quantity numeric(10, 2) not null default 1,
    unit_price numeric(12, 0) not null default 0,
    amount numeric(12, 0) not null default 0,
    ordered_at timestamp with time zone not null default now(),
    status text not null default 'active',
    voided_at timestamp with time zone,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_lines_quantity check (quantity > 0),
    constraint chk_store_order_lines_unit_price check (unit_price >= 0),
    constraint chk_store_order_lines_amount check (amount >= 0),
    constraint chk_store_order_lines_status check (status in ('active', 'voided')),
    constraint uq_store_order_lines_line unique (slip_id, line_no)
);

create table if not exists public.store_checkouts (
    checkout_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    checkout_at timestamp with time zone not null,
    total_amount numeric(12, 0) not null default 0,
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    received_amount numeric(12, 0),
    change_amount numeric(12, 0),
    status text not null default 'draft',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_checkouts_slip unique (slip_id),
    constraint chk_store_checkouts_total_amount check (total_amount >= 0),
    constraint chk_store_checkouts_received_amount check (received_amount is null or received_amount >= 0),
    constraint chk_store_checkouts_change_amount check (change_amount is null or change_amount >= 0),
    constraint chk_store_checkouts_status check (status in ('draft', 'confirmed', 'cancelled'))
);

create index if not exists idx_store_table_master_active
    on public.store_table_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_cast_master_active
    on public.cast_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_store_item_category_master_active
    on public.store_item_category_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_store_item_master_active
    on public.store_item_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_payment_method_master_active
    on public.payment_method_master(company_id, department_id, is_active, sort_order);

create unique index if not exists ux_store_business_days_one_open
    on public.store_business_days(company_id, department_id)
    where status = 'open';

create index if not exists idx_store_business_days_lookup
    on public.store_business_days(company_id, department_id, business_date, status);

create index if not exists idx_store_slips_open
    on public.store_slips(company_id, department_id, status, opened_at);

create index if not exists idx_store_slips_business_day
    on public.store_slips(business_day_id, status);

create index if not exists idx_store_slip_customers_slip_status
    on public.store_slip_customers(slip_id, status);

create index if not exists idx_store_slip_casts_slip
    on public.store_slip_casts(slip_id);

create index if not exists idx_store_order_lines_slip_status
    on public.store_order_lines(slip_id, status);

create index if not exists idx_store_checkouts_date
    on public.store_checkouts(company_id, department_id, checkout_at);

alter table public.store_table_master enable row level security;
alter table public.cast_master enable row level security;
alter table public.store_item_category_master enable row level security;
alter table public.store_item_master enable row level security;
alter table public.payment_method_master enable row level security;
alter table public.store_business_days enable row level security;
alter table public.store_slips enable row level security;
alter table public.store_slip_customers enable row level security;
alter table public.store_slip_casts enable row level security;
alter table public.store_order_lines enable row level security;
alter table public.store_checkouts enable row level security;

drop trigger if exists trg_store_table_master_set_updated_at on public.store_table_master;
create trigger trg_store_table_master_set_updated_at
before update on public.store_table_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_cast_master_set_updated_at on public.cast_master;
create trigger trg_cast_master_set_updated_at
before update on public.cast_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_item_category_master_set_updated_at on public.store_item_category_master;
create trigger trg_store_item_category_master_set_updated_at
before update on public.store_item_category_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_item_master_set_updated_at on public.store_item_master;
create trigger trg_store_item_master_set_updated_at
before update on public.store_item_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_payment_method_master_set_updated_at on public.payment_method_master;
create trigger trg_payment_method_master_set_updated_at
before update on public.payment_method_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_business_days_set_updated_at on public.store_business_days;
create trigger trg_store_business_days_set_updated_at
before update on public.store_business_days
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slips_set_updated_at on public.store_slips;
create trigger trg_store_slips_set_updated_at
before update on public.store_slips
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_customers_set_updated_at on public.store_slip_customers;
create trigger trg_store_slip_customers_set_updated_at
before update on public.store_slip_customers
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_casts_set_updated_at on public.store_slip_casts;
create trigger trg_store_slip_casts_set_updated_at
before update on public.store_slip_casts
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_order_lines_set_updated_at on public.store_order_lines;
create trigger trg_store_order_lines_set_updated_at
before update on public.store_order_lines
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_checkouts_set_updated_at on public.store_checkouts;
create trigger trg_store_checkouts_set_updated_at
before update on public.store_checkouts
for each row execute function public.set_updated_at();

commit;
