begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.store_table_master (
    table_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    table_code text not null,
    table_name text,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_table_master_code unique (company_id, department_id, table_code)
);

create table if not exists public.cast_master (
    cast_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_code text,
    display_name text not null,
    status text not null default 'active',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_cast_master_status check (status in ('active', 'inactive', 'left')),
    constraint uq_cast_master_code unique (company_id, department_id, cast_code)
);

create table if not exists public.store_item_category_master (
    item_category_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    category_code text not null,
    category_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_item_category_master_code unique (company_id, department_id, category_code)
);

create table if not exists public.store_item_master (
    item_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    item_category_id bigint references public.store_item_category_master(item_category_id),
    item_name text not null,
    item_type text not null default 'standard',
    default_price numeric(12, 0) not null default 0,
    is_cast_back_target boolean not null default false,
    cast_back_unit_amount numeric(12, 0) not null default 0,
    cast_back_regular_unit_amount numeric(12, 0) not null default 0,
    cast_back_nomination_unit_amount numeric(12, 0) not null default 0,
    cast_back_type text not null default 'drink',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_item_master_type check (item_type in ('standard', 'karaoke')),
    constraint chk_store_item_master_default_price check (default_price >= 0),
    constraint chk_store_item_master_cast_back_unit_amount check (cast_back_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_regular_unit_amount check (cast_back_regular_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_nomination_unit_amount check (cast_back_nomination_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_type check (cast_back_type in ('drink', 'sales', 'other')),
    constraint uq_store_item_master_name unique (company_id, department_id, item_name)
);

create table if not exists public.store_nomination_back_master (
    nomination_back_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    nomination_type text not null,
    back_type text not null default 'nomination',
    back_unit_amount numeric(12, 0) not null default 0,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_nomination_back_master_type check (nomination_type in ('nomination', 'in_store', 'companion')),
    constraint chk_store_nomination_back_master_back_type check (back_type = 'nomination'),
    constraint chk_store_nomination_back_master_unit_amount check (back_unit_amount >= 0),
    constraint uq_store_nomination_back_master_type unique (company_id, department_id, nomination_type)
);

alter table public.store_item_master
    drop constraint if exists uq_store_item_master_code;

alter table public.store_item_master
    drop column if exists item_code;

alter table public.store_item_master
    add column if not exists sort_order integer not null default 0;

alter table public.store_item_master
    add column if not exists item_type text not null default 'standard';

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_item_master_type'
    ) then
        alter table public.store_item_master
            add constraint chk_store_item_master_type
            check (item_type in ('standard', 'karaoke'));
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'uq_store_item_master_name'
    ) then
        alter table public.store_item_master
            add constraint uq_store_item_master_name unique (company_id, department_id, item_name);
    end if;
end $$;

alter table public.store_item_master
    add column if not exists is_cast_back_target boolean not null default false;

alter table public.store_item_master
    add column if not exists cast_back_unit_amount numeric(12, 0) not null default 0;

alter table public.store_item_master
    add column if not exists cast_back_regular_unit_amount numeric(12, 0) not null default 0;

alter table public.store_item_master
    add column if not exists cast_back_nomination_unit_amount numeric(12, 0) not null default 0;

alter table public.store_item_master
    add column if not exists cast_back_type text not null default 'drink';

update public.store_item_master
   set cast_back_regular_unit_amount = cast_back_unit_amount
 where cast_back_regular_unit_amount = 0
   and cast_back_unit_amount > 0;

with target_departments as (
    select
        d.company_id,
        d.department_id
    from public.department_master d
    where d.is_active = true
),
nomination_types as (
    select *
    from (values
        ('nomination'::text, 10),
        ('in_store'::text, 20),
        ('companion'::text, 30)
    ) as t(nomination_type, sort_order)
)
insert into public.store_nomination_back_master (
    company_id,
    department_id,
    nomination_type,
    back_type,
    back_unit_amount,
    sort_order,
    is_active
)
select
    td.company_id,
    td.department_id,
    nt.nomination_type,
    'nomination',
    0,
    nt.sort_order,
    true
from target_departments td
cross join nomination_types nt
on conflict (company_id, department_id, nomination_type)
do nothing;

with target_departments as (
    select
        d.company_id,
        d.department_id
    from public.department_master d
    where d.is_active = true
),
upsert_categories as (
    insert into public.store_item_category_master (
        company_id,
        department_id,
        category_code,
        category_name,
        sort_order,
        is_active
    )
    select
        td.company_id,
        td.department_id,
        'karaoke',
        'カラオケ',
        9000,
        true
    from target_departments td
    on conflict (company_id, department_id, category_code)
    do update
       set category_name = excluded.category_name,
           sort_order = excluded.sort_order,
           is_active = true,
           updated_at = now()
    returning item_category_id, company_id, department_id
),
karaoke_categories as (
    select item_category_id, company_id, department_id from upsert_categories
    union
    select c.item_category_id, c.company_id, c.department_id
    from public.store_item_category_master c
    join target_departments td
      on td.company_id = c.company_id
     and td.department_id = c.department_id
    where c.category_code = 'karaoke'
)
insert into public.store_item_master (
    company_id,
    department_id,
    item_category_id,
    item_name,
    item_type,
    default_price,
    is_cast_back_target,
    cast_back_unit_amount,
    cast_back_regular_unit_amount,
    cast_back_nomination_unit_amount,
    cast_back_type,
    sort_order,
    is_active
)
select
    kc.company_id,
    kc.department_id,
    kc.item_category_id,
    'カラオケ',
    'karaoke',
    200,
    false,
    0,
    0,
    0,
    'other',
    9000,
    true
from karaoke_categories kc
on conflict (company_id, department_id, item_name)
do update
   set item_category_id = excluded.item_category_id,
       item_type = 'karaoke',
       default_price = 200,
       is_cast_back_target = false,
       cast_back_unit_amount = 0,
       cast_back_regular_unit_amount = 0,
       cast_back_nomination_unit_amount = 0,
       cast_back_type = 'other',
       is_active = true,
       updated_at = now();

create table if not exists public.payment_method_master (
    payment_method_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_code text not null,
    payment_method_name text not null,
    requires_received_amount boolean not null default false,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_payment_method_master_code unique (company_id, department_id, payment_method_code)
);

create table if not exists public.store_business_days (
    business_day_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_date date not null,
    opened_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    status text not null default 'open',
    opened_by text,
    closed_by text,
    memo text,
    drink_delivery_amount numeric(12, 0) not null default 0,
    drink_delivery_amount_entered boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_business_days_status check (status in ('open', 'closed', 'cancelled')),
    constraint chk_store_business_days_drink_delivery_amount check (drink_delivery_amount >= 0),
    constraint chk_store_business_days_closed_at check (closed_at is null or closed_at >= opened_at)
);

create table if not exists public.store_cast_attendance (
    attendance_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint not null references public.store_business_days(business_day_id) on delete cascade,
    business_date date not null,
    cast_id bigint not null references public.cast_master(cast_id),
    attendance_status text not null default 'scheduled',
    clock_in_at timestamp with time zone,
    clock_out_at timestamp with time zone,
    uses_send_service boolean not null default false,
    source text not null default 'opening',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_cast_attendance_status check (attendance_status in ('scheduled', 'checked_in', 'checked_out', 'absent', 'cancelled')),
    constraint chk_store_cast_attendance_source check (source in ('opening', 'manual', 'import')),
    constraint chk_store_cast_attendance_clock_out check (clock_out_at is null or clock_in_at is null or clock_out_at >= clock_in_at),
    constraint uq_store_cast_attendance_day_cast unique (business_day_id, cast_id)
);

create table if not exists public.store_slips (
    slip_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    table_id bigint references public.store_table_master(table_id),
    slip_no text,
    opened_at timestamp with time zone not null,
    closed_at timestamp with time zone,
    status text not null default 'open',
    customer_count integer not null default 0,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slips_status check (status in ('open', 'checked_out', 'cancelled')),
    constraint chk_store_slips_customer_count check (customer_count >= 0),
    constraint chk_store_slips_closed_at check (closed_at is null or closed_at >= opened_at),
    constraint uq_store_slips_slip_no unique (company_id, department_id, slip_no)
);

alter table public.store_slips
    add column if not exists business_day_id bigint references public.store_business_days(business_day_id);

alter table public.store_slips
    add column if not exists business_date date;

alter table public.store_business_days
    add column if not exists drink_delivery_amount numeric(12, 0) not null default 0;

alter table public.store_business_days
    add column if not exists drink_delivery_amount_entered boolean not null default false;

update public.store_business_days
   set drink_delivery_amount_entered = true
 where drink_delivery_amount > 0
   and drink_delivery_amount_entered = false;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_business_days_drink_delivery_amount'
    ) then
        alter table public.store_business_days
            add constraint chk_store_business_days_drink_delivery_amount
            check (drink_delivery_amount >= 0);
    end if;
end $$;

alter table public.store_cast_attendance
    add column if not exists uses_send_service boolean not null default false;

create table if not exists public.store_slip_customers (
    slip_customer_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    customer_label text,
    entered_at timestamp with time zone not null,
    left_at timestamp with time zone,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_customers_status check (status in ('active', 'left', 'cancelled')),
    constraint chk_store_slip_customers_left_at check (left_at is null or left_at >= entered_at),
    constraint uq_store_slip_customers_line unique (slip_id, line_no)
);

create table if not exists public.store_slip_casts (
    slip_cast_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    nomination_type text not null default 'nomination',
    nomination_price numeric(12, 0) not null default 0,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_casts_nomination_type check (nomination_type in ('nomination', 'in_store', 'companion', 'help', 'other')),
    constraint chk_store_slip_casts_nomination_price check (nomination_price >= 0),
    constraint chk_store_slip_casts_status check (status in ('active', 'ended', 'cancelled')),
    constraint chk_store_slip_casts_ended_at check (started_at is null or ended_at is null or ended_at >= started_at)
);

alter table public.store_slip_casts
    add column if not exists nomination_price numeric(12, 0) not null default 0;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_slip_casts_nomination_price'
    ) then
        alter table public.store_slip_casts
            add constraint chk_store_slip_casts_nomination_price
            check (nomination_price >= 0);
    end if;
end $$;

create table if not exists public.store_order_lines (
    order_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    item_id bigint references public.store_item_master(item_id) on delete set null,
    item_name_snapshot text not null,
    quantity numeric(10, 2) not null default 1,
    unit_price numeric(12, 0) not null default 0,
    amount numeric(12, 0) not null default 0,
    ordered_at timestamp with time zone not null default now(),
    status text not null default 'active',
    voided_at timestamp with time zone,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_lines_quantity check (quantity > 0),
    constraint chk_store_order_lines_unit_price check (unit_price >= 0),
    constraint chk_store_order_lines_amount check (amount >= 0),
    constraint chk_store_order_lines_status check (status in ('active', 'voided')),
    constraint uq_store_order_lines_line unique (slip_id, line_no)
);

alter table public.store_order_lines
    drop constraint if exists store_order_lines_item_id_fkey;

alter table public.store_order_lines
    add constraint store_order_lines_item_id_fkey
    foreign key (item_id)
    references public.store_item_master(item_id)
    on delete set null;

create table if not exists public.store_order_line_cast_backs (
    order_line_cast_back_id bigint generated by default as identity primary key,
    order_line_id bigint not null references public.store_order_lines(order_line_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    back_type text not null default 'drink',
    quantity numeric(10, 2) not null default 1,
    back_unit_amount numeric(12, 0) not null default 0,
    back_amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_line_cast_backs_type check (back_type in ('drink', 'sales', 'other')),
    constraint chk_store_order_line_cast_backs_quantity check (quantity > 0),
    constraint chk_store_order_line_cast_backs_unit_amount check (back_unit_amount >= 0),
    constraint chk_store_order_line_cast_backs_amount check (back_amount >= 0),
    constraint chk_store_order_line_cast_backs_status check (status in ('active', 'voided', 'cancelled'))
);

create table if not exists public.store_slip_cast_backs (
    slip_cast_back_id bigint generated by default as identity primary key,
    slip_cast_id bigint not null references public.store_slip_casts(slip_cast_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    nomination_type text not null,
    back_type text not null default 'nomination',
    quantity numeric(10, 2) not null default 1,
    back_unit_amount numeric(12, 0) not null default 0,
    back_amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_cast_backs_nomination_type check (nomination_type in ('nomination', 'in_store', 'companion')),
    constraint chk_store_slip_cast_backs_back_type check (back_type = 'nomination'),
    constraint chk_store_slip_cast_backs_quantity check (quantity > 0),
    constraint chk_store_slip_cast_backs_unit_amount check (back_unit_amount >= 0),
    constraint chk_store_slip_cast_backs_amount check (back_amount >= 0),
    constraint chk_store_slip_cast_backs_status check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_slip_cast_backs_slip_cast unique (slip_cast_id)
);

create table if not exists public.store_slip_charge_lines (
    charge_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    line_no integer not null,
    charge_type text not null,
    line_name text not null,
    quantity numeric(10, 2) not null default 1,
    unit_price numeric(12, 0) not null default 0,
    amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_charge_lines_type check (charge_type in ('adjustment', 'karaoke')),
    constraint chk_store_slip_charge_lines_name check (length(trim(line_name)) > 0),
    constraint chk_store_slip_charge_lines_quantity check (quantity > 0),
    constraint chk_store_slip_charge_lines_adjustment check (charge_type <> 'adjustment' or quantity = 1),
    constraint chk_store_slip_charge_lines_karaoke check (charge_type <> 'karaoke' or (unit_price = 200 and amount >= 0)),
    constraint chk_store_slip_charge_lines_status check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_slip_charge_lines_line unique (slip_id, line_no)
);

do $$
declare
    v_charge record;
    v_order_line_id bigint;
    v_line_no integer;
    v_entered_at timestamp with time zone;
begin
    for v_charge in
        select
            s.slip_id,
            s.business_day_id,
            s.opened_at,
            i.item_id,
            i.item_name,
            i.default_price,
            sum(cl.quantity) as quantity
        from public.store_slip_charge_lines cl
        join public.store_slips s
          on s.slip_id = cl.slip_id
        join public.store_item_master i
          on i.company_id = cl.company_id
         and i.department_id = cl.department_id
         and i.item_type = 'karaoke'
         and i.is_active = true
        where cl.charge_type = 'karaoke'
          and cl.status = 'active'
        group by s.slip_id, s.business_day_id, s.opened_at, i.item_id, i.item_name, i.default_price
    loop
        select coalesce(min(c.entered_at), v_charge.opened_at)
          into v_entered_at
        from public.store_slip_customers c
        where c.slip_id = v_charge.slip_id
          and c.status <> 'cancelled';

        select ol.order_line_id
          into v_order_line_id
        from public.store_order_lines ol
        join public.store_item_master i
          on i.item_id = ol.item_id
        where ol.slip_id = v_charge.slip_id
          and ol.status = 'active'
          and i.item_type = 'karaoke'
        order by ol.line_no asc
        limit 1;

        update public.store_order_lines ol
           set status = 'voided',
               voided_at = coalesce(ol.voided_at, now()),
               updated_at = now()
        from public.store_item_master i
        where i.item_id = ol.item_id
          and ol.slip_id = v_charge.slip_id
          and ol.status = 'active'
          and i.item_type = 'karaoke'
          and (v_order_line_id is null or ol.order_line_id <> v_order_line_id);

        if v_order_line_id is null then
            select coalesce(max(ol.line_no), 0) + 1
              into v_line_no
            from public.store_order_lines ol
            where ol.slip_id = v_charge.slip_id;

            insert into public.store_order_lines (
                slip_id,
                line_no,
                item_id,
                item_name_snapshot,
                quantity,
                unit_price,
                amount,
                ordered_at,
                status
            )
            values (
                v_charge.slip_id,
                v_line_no,
                v_charge.item_id,
                v_charge.item_name,
                v_charge.quantity,
                v_charge.default_price,
                v_charge.default_price * v_charge.quantity,
                v_entered_at,
                'active'
            );
        else
            update public.store_order_lines ol
               set item_id = v_charge.item_id,
                   item_name_snapshot = v_charge.item_name,
                   quantity = v_charge.quantity,
                   unit_price = v_charge.default_price,
                   amount = v_charge.default_price * v_charge.quantity,
                   ordered_at = v_entered_at,
                   status = 'active',
                   voided_at = null,
                   updated_at = now()
             where ol.order_line_id = v_order_line_id;
        end if;
    end loop;

    update public.store_slip_charge_lines cl
       set status = 'voided',
           updated_at = now()
     where cl.charge_type = 'karaoke'
       and cl.status = 'active';
end $$;

create table if not exists public.store_checkouts (
    checkout_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    checkout_at timestamp with time zone not null,
    total_amount numeric(12, 0) not null default 0,
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    received_amount numeric(12, 0),
    change_amount numeric(12, 0),
    status text not null default 'draft',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_checkouts_slip unique (slip_id),
    constraint chk_store_checkouts_total_amount check (total_amount >= 0),
    constraint chk_store_checkouts_received_amount check (received_amount is null or received_amount >= 0),
    constraint chk_store_checkouts_change_amount check (change_amount is null or change_amount >= 0),
    constraint chk_store_checkouts_status check (status in ('draft', 'confirmed', 'cancelled'))
);

alter table public.store_checkouts
    add column if not exists subtotal_amount numeric(12, 0) not null default 0;

alter table public.store_checkouts
    add column if not exists service_tax_amount numeric(12, 0) not null default 0;

create table if not exists public.store_checkout_payments (
    checkout_payment_id bigint generated by default as identity primary key,
    checkout_id bigint not null references public.store_checkouts(checkout_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    payment_method_code text not null,
    payment_method_name text not null,
    amount numeric(12, 0) not null default 0,
    status text not null default 'confirmed',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_checkout_payments_amount check (amount >= 0),
    constraint chk_store_checkout_payments_status check (status in ('confirmed', 'cancelled'))
);

create table if not exists public.store_slip_cast_sales_adjustments (
    adjustment_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    checkout_id bigint not null references public.store_checkouts(checkout_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    slip_cast_id bigint not null references public.store_slip_casts(slip_cast_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    source_amount_type text not null default 'total',
    split_mode text not null default 'split',
    base_amount numeric(12, 0) not null default 0,
    sales_amount numeric(12, 0) not null default 0,
    status text not null default 'confirmed',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_slip_cast_sales_adjustments_slip_cast unique (slip_id, slip_cast_id),
    constraint chk_store_slip_cast_sales_adjustments_source check (source_amount_type in ('subtotal', 'total')),
    constraint chk_store_slip_cast_sales_adjustments_split check (split_mode in ('split', 'full')),
    constraint chk_store_slip_cast_sales_adjustments_base_amount check (base_amount >= 0),
    constraint chk_store_slip_cast_sales_adjustments_sales_amount check (sales_amount >= 0),
    constraint chk_store_slip_cast_sales_adjustments_status check (status in ('confirmed', 'cancelled'))
);

create index if not exists idx_store_table_master_active
    on public.store_table_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_cast_master_active
    on public.cast_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_store_item_category_master_active
    on public.store_item_category_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_store_item_master_active
    on public.store_item_master(company_id, department_id, is_active, sort_order);

create unique index if not exists ux_store_item_master_karaoke_active
    on public.store_item_master(company_id, department_id)
    where item_type = 'karaoke' and is_active = true;

create index if not exists idx_payment_method_master_active
    on public.payment_method_master(company_id, department_id, is_active, sort_order);

create unique index if not exists ux_store_business_days_one_open
    on public.store_business_days(company_id, department_id)
    where status = 'open';

create index if not exists idx_store_business_days_lookup
    on public.store_business_days(company_id, department_id, business_date, status);

create index if not exists idx_store_business_days_open_department
    on public.store_business_days(department_id, opened_at desc)
    where status = 'open';

create index if not exists idx_store_cast_attendance_day_status
    on public.store_cast_attendance(company_id, department_id, business_day_id, attendance_status);

create index if not exists idx_store_cast_attendance_department_day_status
    on public.store_cast_attendance(department_id, business_day_id, attendance_status, cast_id);

create index if not exists idx_store_cast_attendance_cast
    on public.store_cast_attendance(cast_id, business_date);

create index if not exists idx_store_slips_open
    on public.store_slips(company_id, department_id, status, opened_at);

create index if not exists idx_store_slips_business_day
    on public.store_slips(business_day_id, status);

create index if not exists idx_store_slips_department_business_day
    on public.store_slips(department_id, business_day_id, opened_at);

create index if not exists idx_store_slip_customers_slip_status
    on public.store_slip_customers(slip_id, status);

create index if not exists idx_store_slip_casts_slip
    on public.store_slip_casts(slip_id);

create index if not exists idx_store_order_lines_slip_status
    on public.store_order_lines(slip_id, status);

create index if not exists idx_store_order_line_cast_backs_cast_date
    on public.store_order_line_cast_backs(company_id, department_id, cast_id, business_date, status);

create index if not exists idx_store_order_line_cast_backs_line
    on public.store_order_line_cast_backs(order_line_id, status);

create index if not exists idx_store_nomination_back_master_department
    on public.store_nomination_back_master(department_id, is_active, sort_order);

create index if not exists idx_store_slip_cast_backs_cast_date
    on public.store_slip_cast_backs(company_id, department_id, cast_id, business_date, status);

create index if not exists idx_store_slip_cast_backs_slip
    on public.store_slip_cast_backs(slip_id, status);

create index if not exists idx_store_slip_cast_backs_slip_cast
    on public.store_slip_cast_backs(slip_cast_id, status);

create index if not exists idx_store_slip_charge_lines_slip_status
    on public.store_slip_charge_lines(slip_id, charge_type, status);

create index if not exists idx_store_slip_charge_lines_day
    on public.store_slip_charge_lines(company_id, department_id, business_day_id, status);

create index if not exists idx_store_checkouts_date
    on public.store_checkouts(company_id, department_id, checkout_at);

create index if not exists idx_store_checkouts_slip_status
    on public.store_checkouts(slip_id, status);

create index if not exists idx_store_checkout_payments_checkout
    on public.store_checkout_payments(checkout_id, status);

create index if not exists idx_store_slip_cast_sales_adjustments_day
    on public.store_slip_cast_sales_adjustments(company_id, department_id, business_day_id, status);

create index if not exists idx_store_slip_cast_sales_adjustments_slip
    on public.store_slip_cast_sales_adjustments(slip_id, status);

create index if not exists idx_store_slip_cast_sales_adjustments_cast_date
    on public.store_slip_cast_sales_adjustments(company_id, department_id, cast_id, business_date, status);

alter table public.store_table_master enable row level security;
alter table public.cast_master enable row level security;
alter table public.store_item_category_master enable row level security;
alter table public.store_item_master enable row level security;
alter table public.store_nomination_back_master enable row level security;
alter table public.payment_method_master enable row level security;
alter table public.store_business_days enable row level security;
alter table public.store_cast_attendance enable row level security;
alter table public.store_slips enable row level security;
alter table public.store_slip_customers enable row level security;
alter table public.store_slip_casts enable row level security;
alter table public.store_order_lines enable row level security;
alter table public.store_order_line_cast_backs enable row level security;
alter table public.store_slip_cast_backs enable row level security;
alter table public.store_slip_charge_lines enable row level security;
alter table public.store_checkouts enable row level security;
alter table public.store_checkout_payments enable row level security;
alter table public.store_slip_cast_sales_adjustments enable row level security;

drop trigger if exists trg_store_table_master_set_updated_at on public.store_table_master;
create trigger trg_store_table_master_set_updated_at
before update on public.store_table_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_cast_master_set_updated_at on public.cast_master;
create trigger trg_cast_master_set_updated_at
before update on public.cast_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_item_category_master_set_updated_at on public.store_item_category_master;
create trigger trg_store_item_category_master_set_updated_at
before update on public.store_item_category_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_item_master_set_updated_at on public.store_item_master;
create trigger trg_store_item_master_set_updated_at
before update on public.store_item_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_nomination_back_master_set_updated_at on public.store_nomination_back_master;
create trigger trg_store_nomination_back_master_set_updated_at
before update on public.store_nomination_back_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_payment_method_master_set_updated_at on public.payment_method_master;
create trigger trg_payment_method_master_set_updated_at
before update on public.payment_method_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_business_days_set_updated_at on public.store_business_days;
create trigger trg_store_business_days_set_updated_at
before update on public.store_business_days
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_cast_attendance_set_updated_at on public.store_cast_attendance;
create trigger trg_store_cast_attendance_set_updated_at
before update on public.store_cast_attendance
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slips_set_updated_at on public.store_slips;
create trigger trg_store_slips_set_updated_at
before update on public.store_slips
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_customers_set_updated_at on public.store_slip_customers;
create trigger trg_store_slip_customers_set_updated_at
before update on public.store_slip_customers
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_casts_set_updated_at on public.store_slip_casts;
create trigger trg_store_slip_casts_set_updated_at
before update on public.store_slip_casts
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_order_lines_set_updated_at on public.store_order_lines;
create trigger trg_store_order_lines_set_updated_at
before update on public.store_order_lines
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_order_line_cast_backs_set_updated_at on public.store_order_line_cast_backs;
create trigger trg_store_order_line_cast_backs_set_updated_at
before update on public.store_order_line_cast_backs
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_cast_backs_set_updated_at on public.store_slip_cast_backs;
create trigger trg_store_slip_cast_backs_set_updated_at
before update on public.store_slip_cast_backs
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_charge_lines_set_updated_at on public.store_slip_charge_lines;
create trigger trg_store_slip_charge_lines_set_updated_at
before update on public.store_slip_charge_lines
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_checkouts_set_updated_at on public.store_checkouts;
create trigger trg_store_checkouts_set_updated_at
before update on public.store_checkouts
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_checkout_payments_set_updated_at on public.store_checkout_payments;
create trigger trg_store_checkout_payments_set_updated_at
before update on public.store_checkout_payments
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_cast_sales_adjustments_set_updated_at on public.store_slip_cast_sales_adjustments;
create trigger trg_store_slip_cast_sales_adjustments_set_updated_at
before update on public.store_slip_cast_sales_adjustments
for each row execute function public.set_updated_at();

commit;
