-- store_rpc_functions.sql
--
-- This file is intentionally non-executable. The store RPC definitions were split
-- by feature to make review and maintenance easier. Execute the files below in
-- this order when applying the full RPC set:
--
--   1. Sql/store_rpc/00_schema.sql
--   2. Sql/store_rpc/01_business_day.sql
--   3. Sql/store_rpc/02_store_masters.sql
--   4. Sql/store_rpc/03_slips.sql
--   5. Sql/store_rpc/04_orders.sql
--   6. Sql/store_rpc/05_checkout.sql
--   7. Sql/store_rpc/06_receipts.sql
--   8. Sql/store_rpc/07_cast_sales_adjustments.sql
--   9. Sql/store_rpc/11_pricing.sql
--  10. Sql/store_rpc/12_pricing_system_items.sql
--  11. Sql/store_rpc/08_checkout_ready.sql
--  12. Sql/store_rpc/09_business_home_snapshot.sql
--  13. Sql/store_rpc/10_business_home_flush.sql
--  14. Sql/store_rpc/12_daily_report.sql
--  15. Sql/store_rpc/13_accounting_snapshot_guards.sql
--  16. Sql/store_rpc/14_operational_read_models.sql
--  17. Sql/store_rpc/99_grants.sql
--
-- Keep function names, argument lists, return columns, and direct execute revokes
-- in the split files aligned with the current C# RPC callers and prosper-rpc allowlist.
