begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

alter table public.department_master
    add column if not exists attendance_minute_step integer;

alter table public.department_master
    add column if not exists cast_sales_amount_basis text;

alter table public.department_master
    add column if not exists cast_sales_split_mode text;

update public.department_master
   set attendance_minute_step = 15
 where attendance_minute_step is null
    or attendance_minute_step not in (5, 10, 15, 20, 30, 60);

update public.department_master
   set cast_sales_amount_basis = 'total'
 where cast_sales_amount_basis is null
    or cast_sales_amount_basis not in ('subtotal', 'total');

update public.department_master
   set cast_sales_split_mode = 'split'
 where cast_sales_split_mode is null
    or cast_sales_split_mode not in ('split', 'full');

alter table public.department_master
    alter column attendance_minute_step set default 15,
    alter column attendance_minute_step set not null,
    alter column cast_sales_amount_basis set default 'total',
    alter column cast_sales_amount_basis set not null,
    alter column cast_sales_split_mode set default 'split',
    alter column cast_sales_split_mode set not null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_department_master_attendance_minute_step'
    ) then
        alter table public.department_master
            add constraint chk_department_master_attendance_minute_step
            check (attendance_minute_step in (5, 10, 15, 20, 30, 60));
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_department_master_cast_sales_amount_basis'
    ) then
        alter table public.department_master
            add constraint chk_department_master_cast_sales_amount_basis
            check (cast_sales_amount_basis in ('subtotal', 'total'));
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_department_master_cast_sales_split_mode'
    ) then
        alter table public.department_master
            add constraint chk_department_master_cast_sales_split_mode
            check (cast_sales_split_mode in ('split', 'full'));
    end if;
end $$;

create table if not exists public.store_table_master (
    table_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    table_code text not null,
    table_name text,
    table_category_no smallint not null default 0,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_table_master_code unique (company_id, department_id, table_code),
    constraint chk_store_table_master_category_no check (table_category_no between 0 and 9)
);

alter table public.store_table_master
    add column if not exists table_category_no smallint not null default 0;

do $$
begin
    if not exists (
        select 1
        from pg_constraint c
        where c.conrelid = 'public.store_table_master'::regclass
          and c.conname = 'chk_store_table_master_category_no'
    ) then
        alter table public.store_table_master
            add constraint chk_store_table_master_category_no
            check (table_category_no between 0 and 9);
    end if;
end $$;

create table if not exists public.cast_master (
    cast_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_code text,
    display_name text not null,
    drink_memo text,
    status text not null default 'active',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_cast_master_status check (status in ('active', 'inactive', 'left')),
    constraint chk_cast_master_drink_memo_length check (char_length(drink_memo) <= 30),
    constraint uq_cast_master_code unique (company_id, department_id, cast_code)
);

alter table public.cast_master
    add column if not exists drink_memo text;

alter table public.cast_master
    drop constraint if exists chk_cast_master_drink_memo_length;

alter table public.cast_master
    add constraint chk_cast_master_drink_memo_length
    check (char_length(drink_memo) <= 30);

create table if not exists public.store_item_category_master (
    item_category_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    category_code text not null,
    category_name text not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_store_item_category_master_code unique (company_id, department_id, category_code)
);

create table if not exists public.store_item_master (
    item_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    item_category_id bigint references public.store_item_category_master(item_category_id),
    item_name text not null,
    item_type text not null default 'standard',
    default_price numeric(12, 0) not null default 0,
    is_cast_back_target boolean not null default false,
    cast_back_unit_amount numeric(12, 0) not null default 0,
    cast_back_regular_unit_amount numeric(12, 0) not null default 0,
    cast_back_nomination_unit_amount numeric(12, 0) not null default 0,
    cast_back_type text not null default 'drink',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_item_master_type check (item_type in ('standard', 'karaoke', 'nomination_fee', 'set_fee', 'extension_fee')),
    constraint chk_store_item_master_default_price check (default_price >= 0),
    constraint chk_store_item_master_cast_back_unit_amount check (cast_back_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_regular_unit_amount check (cast_back_regular_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_nomination_unit_amount check (cast_back_nomination_unit_amount >= 0),
    constraint chk_store_item_master_cast_back_type check (cast_back_type in ('drink', 'sales', 'other')),
    constraint uq_store_item_master_name unique (company_id, department_id, item_name)
);

create table if not exists public.store_nomination_back_master (
    nomination_back_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    nomination_kind text not null,
    nomination_type text not null,
    display_name text not null,
    companion_time time,
    back_type text not null default 'nomination',
    back_unit_amount numeric(12, 0) not null default 0,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_nomination_back_master_type check (nomination_type in ('nomination', 'in_store', 'companion')),
    constraint chk_store_nomination_back_master_kind check (length(trim(nomination_kind)) > 0),
    constraint chk_store_nomination_back_master_display check (length(trim(display_name)) > 0),
    constraint chk_store_nomination_back_master_companion_time check (
        (nomination_type = 'companion' and companion_time is not null) or
        (nomination_type <> 'companion' and companion_time is null)
    ),
    constraint chk_store_nomination_back_master_back_type check (back_type = 'nomination'),
    constraint chk_store_nomination_back_master_unit_amount check (back_unit_amount >= 0),
    constraint uq_store_nomination_back_master_kind unique (company_id, department_id, nomination_kind)
);

alter table public.store_nomination_back_master
    add column if not exists nomination_kind text not null default 'nomination';

alter table public.store_nomination_back_master
    add column if not exists display_name text not null default '';

alter table public.store_nomination_back_master
    add column if not exists companion_time time;

update public.store_nomination_back_master
   set nomination_kind = case nomination_type
       when 'companion' then 'companion_until_1929'
       else nomination_type
   end
 where nullif(trim(coalesce(nomination_kind, '')), '') is null
    or nomination_kind = nomination_type
    or (nomination_kind = 'nomination' and nomination_type <> 'nomination');

update public.store_nomination_back_master
   set display_name = case nomination_type
       when 'in_store' then '場内指名'
       when 'companion' then '同伴'
       else '本指名'
   end
 where nullif(trim(coalesce(display_name, '')), '') is null;

update public.store_nomination_back_master
   set companion_time = time '19:29'
 where nomination_type = 'companion'
   and companion_time is null;

update public.store_nomination_back_master
   set companion_time = null
 where nomination_type <> 'companion'
   and companion_time is not null;

alter table public.store_nomination_back_master
    alter column nomination_kind set default 'nomination';

alter table public.store_nomination_back_master
    alter column nomination_kind set not null;

alter table public.store_nomination_back_master
    alter column display_name set not null;

alter table public.store_nomination_back_master
    drop constraint if exists uq_store_nomination_back_master_type;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'uq_store_nomination_back_master_kind'
    ) then
        alter table public.store_nomination_back_master
            add constraint uq_store_nomination_back_master_kind
            unique (company_id, department_id, nomination_kind);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_nomination_back_master_kind'
    ) then
        alter table public.store_nomination_back_master
            add constraint chk_store_nomination_back_master_kind
            check (length(trim(nomination_kind)) > 0);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_nomination_back_master_display'
    ) then
        alter table public.store_nomination_back_master
            add constraint chk_store_nomination_back_master_display
            check (length(trim(display_name)) > 0);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_nomination_back_master_companion_time'
    ) then
        alter table public.store_nomination_back_master
            add constraint chk_store_nomination_back_master_companion_time
            check (
                (nomination_type = 'companion' and companion_time is not null) or
                (nomination_type <> 'companion' and companion_time is null)
            );
    end if;
end $$;

alter table public.store_item_master
    drop constraint if exists uq_store_item_master_code;

alter table public.store_item_master
    drop column if exists item_code;

alter table public.store_item_master
    add column if not exists sort_order integer not null default 0;

alter table public.store_item_master
    add column if not exists item_type text not null default 'standard';

alter table public.store_item_master
    drop constraint if exists chk_store_item_master_type;

alter table public.store_item_master
    add constraint chk_store_item_master_type
    check (item_type in ('standard', 'karaoke', 'nomination_fee', 'set_fee', 'extension_fee'));

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'uq_store_item_master_name'
    ) then
        alter table public.store_item_master
            add constraint uq_store_item_master_name unique (company_id, department_id, item_name);
    end if;
end $$;

alter table public.store_item_master
    add column if not exists is_cast_back_target boolean not null default false;

alter table public.store_item_master
    add column if not exists cast_back_unit_amount numeric(12, 0) not null default 0;

alter table public.store_item_master
    add column if not exists cast_back_regular_unit_amount numeric(12, 0) not null default 0;

alter table public.store_item_master
    add column if not exists cast_back_nomination_unit_amount numeric(12, 0) not null default 0;

alter table public.store_item_master
    add column if not exists cast_back_type text not null default 'drink';

update public.store_item_master
   set cast_back_regular_unit_amount = cast_back_unit_amount
 where cast_back_regular_unit_amount = 0
   and cast_back_unit_amount > 0;

with target_departments as (
    select
        d.company_id,
        d.department_id
    from public.department_master d
    where d.is_active = true
),
nomination_types as (
    select *
    from (values
        ('nomination'::text, 'nomination'::text, '本指名'::text, null::time, 10),
        ('in_store'::text, 'in_store'::text, '場内指名'::text, null::time, 20),
        ('companion_until_1929'::text, 'companion'::text, '同伴 19:29まで'::text, time '19:29', 30),
        ('companion_until_1959'::text, 'companion'::text, '同伴 19:59まで'::text, time '19:59', 40),
        ('companion_until_2059'::text, 'companion'::text, '同伴 20:59まで'::text, time '20:59', 50),
        ('companion_after_2100'::text, 'companion'::text, '同伴 21:00以降'::text, time '21:00', 60)
    ) as t(nomination_kind, nomination_type, display_name, companion_time, sort_order)
)
insert into public.store_nomination_back_master (
    company_id,
    department_id,
    nomination_kind,
    nomination_type,
    display_name,
    companion_time,
    back_type,
    back_unit_amount,
    sort_order,
    is_active
)
select
    td.company_id,
    td.department_id,
    nt.nomination_kind,
    nt.nomination_type,
    nt.display_name,
    nt.companion_time,
    'nomination',
    1000,
    nt.sort_order,
    true
from target_departments td
cross join nomination_types nt
where true
on conflict (company_id, department_id, nomination_kind)
do update
   set nomination_type = excluded.nomination_type,
       display_name = excluded.display_name,
       companion_time = excluded.companion_time,
       back_type = 'nomination',
       back_unit_amount = 1000,
       sort_order = excluded.sort_order,
       is_active = true,
       updated_at = now();

with target_departments as (
    select
        d.company_id,
        d.department_id
    from public.department_master d
    where d.is_active = true
),
upsert_categories as (
    insert into public.store_item_category_master (
        company_id,
        department_id,
        category_code,
        category_name,
        sort_order,
        is_active
    )
    select
        td.company_id,
        td.department_id,
        'system',
        'システム',
        9000,
        true
    from target_departments td
    where true
    on conflict (company_id, department_id, category_code)
    do update
       set category_name = excluded.category_name,
           sort_order = excluded.sort_order,
           is_active = true,
           updated_at = now()
    returning item_category_id, company_id, department_id
),
system_categories as (
    select item_category_id, company_id, department_id from upsert_categories
    union
    select c.item_category_id, c.company_id, c.department_id
    from public.store_item_category_master c
    join target_departments td
      on td.company_id = c.company_id
     and td.department_id = c.department_id
    where c.category_code = 'system'
)
insert into public.store_item_master (
    company_id,
    department_id,
    item_category_id,
    item_name,
    item_type,
    default_price,
    is_cast_back_target,
    cast_back_unit_amount,
    cast_back_regular_unit_amount,
    cast_back_nomination_unit_amount,
    cast_back_type,
    sort_order,
    is_active
)
select
    sc.company_id,
    sc.department_id,
    sc.item_category_id,
    'カラオケ',
    'karaoke',
    200,
    false,
    0,
    0,
    0,
    'other',
    9000,
    true
from system_categories sc
where true
on conflict (company_id, department_id, item_name)
do update
   set item_category_id = excluded.item_category_id,
       item_type = 'karaoke',
       default_price = 200,
       is_cast_back_target = false,
       cast_back_unit_amount = 0,
       cast_back_regular_unit_amount = 0,
       cast_back_nomination_unit_amount = 0,
       cast_back_type = 'other',
       is_active = true,
       updated_at = now();

-- カラオケとカテゴリ未設定の商品は操作不可のシステム商品としてまとめます。
-- 注文行のカテゴリスナップショットは商品マスタ更新時点の値を保持するため、過去の会計明細は変わりません。
with system_categories as (
    select
        c.item_category_id,
        c.company_id,
        c.department_id
    from public.store_item_category_master c
    where c.category_code = 'system'
)
update public.store_item_master i
   set item_category_id = sc.item_category_id,
       updated_at = now()
  from system_categories sc
 where sc.company_id = i.company_id
   and sc.department_id = i.department_id
   and (
       i.item_type <> 'standard'
       or i.item_category_id is null
   );

-- 旧カラオケカテゴリは商品移動後に非表示にします。履歴と管理画面上の削除可否は残します。
update public.store_item_category_master c
   set is_active = false,
       updated_at = now()
 where c.category_code = 'karaoke'
   and not exists (
       select 1
       from public.store_item_master i
       where i.item_category_id = c.item_category_id
   );

with target_departments as (
    select
        d.company_id,
        d.department_id
    from public.department_master d
    where d.is_active = true
),
upsert_categories as (
    insert into public.store_item_category_master (
        company_id,
        department_id,
        category_code,
        category_name,
        sort_order,
        is_active
    )
    select
        td.company_id,
        td.department_id,
        'system',
        'システム',
        9010,
        true
    from target_departments td
    where true
    on conflict (company_id, department_id, category_code)
    do update
       set category_name = excluded.category_name,
           sort_order = excluded.sort_order,
           is_active = true,
           updated_at = now()
    returning item_category_id, company_id, department_id
),
system_categories as (
    select item_category_id, company_id, department_id from upsert_categories
    union
    select c.item_category_id, c.company_id, c.department_id
    from public.store_item_category_master c
    join target_departments td
      on td.company_id = c.company_id
     and td.department_id = c.department_id
    where c.category_code = 'system'
)
insert into public.store_item_master (
    company_id,
    department_id,
    item_category_id,
    item_name,
    item_type,
    default_price,
    is_cast_back_target,
    cast_back_unit_amount,
    cast_back_regular_unit_amount,
    cast_back_nomination_unit_amount,
    cast_back_type,
    sort_order,
    is_active
)
select
    sc.company_id,
    sc.department_id,
    sc.item_category_id,
    '指名料金',
    'nomination_fee',
    0,
    false,
    0,
    0,
    0,
    'other',
    9010,
    true
from system_categories sc
where true
on conflict (company_id, department_id, item_name)
do update
   set item_category_id = excluded.item_category_id,
       item_type = 'nomination_fee',
       default_price = 0,
       is_cast_back_target = false,
       cast_back_unit_amount = 0,
       cast_back_regular_unit_amount = 0,
       cast_back_nomination_unit_amount = 0,
       cast_back_type = 'other',
       is_active = true,
       updated_at = now();

create table if not exists public.payment_method_master (
    payment_method_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_code text not null,
    payment_method_name text not null,
    requires_received_amount boolean not null default false,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_payment_method_master_code unique (company_id, department_id, payment_method_code)
);

create table if not exists public.store_business_days (
    business_day_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_date date not null,
    opened_at timestamp with time zone not null default now(),
    closed_at timestamp with time zone,
    status text not null default 'open',
    opened_by text,
    closed_by text,
    memo text,
    drink_delivery_amount numeric(12, 0) not null default 0,
    drink_delivery_amount_entered boolean not null default false,
    business_ui_revision bigint not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_business_days_status check (status in ('open', 'closed', 'cancelled')),
    constraint chk_store_business_days_drink_delivery_amount check (drink_delivery_amount >= 0),
    constraint chk_store_business_days_closed_at check (closed_at is null or closed_at >= opened_at)
);

create table if not exists public.store_cast_attendance (
    attendance_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint not null references public.store_business_days(business_day_id) on delete cascade,
    business_date date not null,
    cast_id bigint not null references public.cast_master(cast_id),
    attendance_status text not null default 'scheduled',
    clock_in_at timestamp with time zone,
    clock_out_at timestamp with time zone,
    uses_send_service boolean not null default false,
    source text not null default 'opening',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_cast_attendance_status check (attendance_status in ('scheduled', 'checked_in', 'checked_out', 'absent', 'cancelled')),
    constraint chk_store_cast_attendance_source check (source in ('opening', 'manual', 'import')),
    constraint chk_store_cast_attendance_clock_out check (clock_out_at is null or clock_in_at is null or clock_out_at >= clock_in_at),
    constraint uq_store_cast_attendance_day_cast unique (business_day_id, cast_id)
);

create table if not exists public.store_slips (
    slip_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    -- 卓番マスタは物理削除できるため、IDは履歴上の識別子として保持しFKを張りません。
    table_id bigint,
    table_code_snapshot text,
    table_name_snapshot text,
    slip_no text,
    opened_at timestamp with time zone not null,
    closed_at timestamp with time zone,
    status text not null default 'open',
    customer_count integer not null default 0,
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slips_status check (status in ('open', 'checkout_ready', 'checked_out', 'cancelled')),
    constraint chk_store_slips_customer_count check (customer_count >= 0),
    constraint chk_store_slips_closed_at check (closed_at is null or closed_at >= opened_at),
    constraint uq_store_slips_slip_no unique (company_id, department_id, slip_no)
);

alter table public.store_slips
    drop constraint if exists chk_store_slips_status;

alter table public.store_slips
    add constraint chk_store_slips_status
    check (status in ('open', 'checkout_ready', 'checked_out', 'cancelled'));

alter table public.store_slips
    add column if not exists business_day_id bigint references public.store_business_days(business_day_id);

alter table public.store_slips
    add column if not exists business_date date;

alter table public.store_slips
    add column if not exists table_code_snapshot text;

alter table public.store_slips
    add column if not exists table_name_snapshot text;

alter table public.store_slips
    drop constraint if exists store_slips_table_id_fkey;

-- 既存伝票にも現在の卓番表示を一度だけ固定します。
-- 締め済み営業日の更新ガードが既に存在する環境でも、この移行だけは明示的に迂回します。
-- 既存の監査時刻と営業中画面revisionは移行前の値を保つため、該当トリガーだけを一時停止します。
do $$
declare
    v_previous_setting text;
    v_updated_at_trigger "char";
    v_revision_trigger "char";
begin
    select t.tgenabled
      into v_updated_at_trigger
      from pg_trigger t
     where t.tgrelid = 'public.store_slips'::regclass
       and t.tgname = 'trg_store_slips_set_updated_at'
       and not t.tgisinternal;

    select t.tgenabled
      into v_revision_trigger
      from pg_trigger t
     where t.tgrelid = 'public.store_slips'::regclass
       and t.tgname = 'trg_store_slips_business_ui_revision'
       and not t.tgisinternal;

    if v_updated_at_trigger is not null then
        alter table public.store_slips disable trigger trg_store_slips_set_updated_at;
    end if;

    if v_revision_trigger is not null then
        alter table public.store_slips disable trigger trg_store_slips_business_ui_revision;
    end if;

    v_previous_setting := current_setting('store.allow_closed_day_mutation', true);
    perform set_config('store.allow_closed_day_mutation', 'on', true);

    update public.store_slips s
       set table_code_snapshot = coalesce(s.table_code_snapshot, t.table_code),
           table_name_snapshot = coalesce(s.table_name_snapshot, t.table_name)
     from public.store_table_master t
     where t.table_id = s.table_id
       and s.table_code_snapshot is null;

    perform set_config('store.allow_closed_day_mutation', coalesce(v_previous_setting, ''), true);

    if v_updated_at_trigger = 'O' then
        alter table public.store_slips enable trigger trg_store_slips_set_updated_at;
    elsif v_updated_at_trigger = 'R' then
        alter table public.store_slips enable replica trigger trg_store_slips_set_updated_at;
    elsif v_updated_at_trigger = 'A' then
        alter table public.store_slips enable always trigger trg_store_slips_set_updated_at;
    end if;

    if v_revision_trigger = 'O' then
        alter table public.store_slips enable trigger trg_store_slips_business_ui_revision;
    elsif v_revision_trigger = 'R' then
        alter table public.store_slips enable replica trigger trg_store_slips_business_ui_revision;
    elsif v_revision_trigger = 'A' then
        alter table public.store_slips enable always trigger trg_store_slips_business_ui_revision;
    end if;
end $$;

alter table public.store_business_days
    add column if not exists drink_delivery_amount numeric(12, 0) not null default 0;

alter table public.store_business_days
    add column if not exists drink_delivery_amount_entered boolean not null default false;

-- 営業中トップの全伝票スナップショット用の単調増加番号。
-- 業務データの版ではなく、クライアントが到着順の古い応答を捨てるための番号です。
alter table public.store_business_days
    add column if not exists business_ui_revision bigint not null default 0;

update public.store_business_days
   set drink_delivery_amount_entered = true
 where drink_delivery_amount > 0
   and drink_delivery_amount_entered = false;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_business_days_drink_delivery_amount'
    ) then
        alter table public.store_business_days
            add constraint chk_store_business_days_drink_delivery_amount
            check (drink_delivery_amount >= 0);
    end if;
end $$;

alter table public.store_cast_attendance
    add column if not exists uses_send_service boolean not null default false;

create table if not exists public.store_slip_customers (
    slip_customer_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    customer_label text,
    entered_at timestamp with time zone not null,
    left_at timestamp with time zone,
    left_at_source text,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_customers_status check (status in ('active', 'left', 'cancelled')),
    constraint chk_store_slip_customers_left_at check (left_at is null or left_at >= entered_at),
    constraint chk_store_slip_customers_left_at_source check (left_at_source in ('manual', 'accounting_slip')),
    constraint uq_store_slip_customers_line unique (slip_id, line_no)
);

alter table public.store_slip_customers
    add column if not exists left_at_source text;

alter table public.store_slip_customers
    alter column left_at_source drop not null;

alter table public.store_slip_customers
    alter column left_at_source drop default;

alter table public.store_slip_customers
    drop constraint if exists chk_store_slip_customers_left_at_source;

alter table public.store_slip_customers
    add constraint chk_store_slip_customers_left_at_source
    check (left_at_source in ('manual', 'accounting_slip'));

create table if not exists public.store_slip_casts (
    slip_cast_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    nomination_kind text not null default 'nomination',
    nomination_type text not null default 'nomination',
    nomination_price numeric(12, 0) not null default 0,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_casts_nomination_type check (nomination_type in ('nomination', 'in_store', 'companion', 'help', 'other')),
    constraint chk_store_slip_casts_nomination_price check (nomination_price >= 0),
    constraint chk_store_slip_casts_status check (status in ('active', 'ended', 'cancelled')),
    constraint chk_store_slip_casts_ended_at check (started_at is null or ended_at is null or ended_at >= started_at)
);

alter table public.store_slip_casts
    add column if not exists nomination_kind text not null default 'nomination';

update public.store_slip_casts
   set nomination_kind = case
       when nomination_type = 'in_store' then 'in_store'
       when nomination_type = 'companion' then case to_char(started_at at time zone 'Asia/Tokyo', 'HH24:MI')
           when '19:29' then 'companion_until_1929'
           when '19:59' then 'companion_until_1959'
           when '20:59' then 'companion_until_2059'
           else 'companion_after_2100'
       end
       else 'nomination'
   end
 where nomination_kind = 'nomination'
   and nomination_type <> 'nomination';

alter table public.store_slip_casts
    add column if not exists nomination_price numeric(12, 0) not null default 0;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_store_slip_casts_nomination_price'
    ) then
        alter table public.store_slip_casts
            add constraint chk_store_slip_casts_nomination_price
            check (nomination_price >= 0);
    end if;
end $$;

create table if not exists public.store_order_lines (
    order_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    line_no integer not null,
    -- 商品・カテゴリマスタは物理削除できるため、IDと明細snapshotを履歴として保持しFKを張りません。
    item_id bigint,
    item_name_snapshot text not null,
    item_category_id_snapshot bigint,
    item_category_code_snapshot text,
    item_category_name_snapshot text,
    quantity numeric(10, 2) not null default 1,
    unit_price numeric(12, 0) not null default 0,
    amount numeric(12, 0) not null default 0,
    ordered_at timestamp with time zone not null default now(),
    status text not null default 'active',
    voided_at timestamp with time zone,
    memo text,
    source_type text,
    source_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_lines_quantity check (quantity > 0),
    constraint chk_store_order_lines_unit_price check (unit_price >= 0),
    constraint chk_store_order_lines_amount check (amount >= 0),
    constraint chk_store_order_lines_status check (status in ('active', 'voided')),
    constraint chk_store_order_lines_source_type check (source_type is null or source_type in ('nomination_fee', 'automatic_pricing')),
    constraint uq_store_order_lines_line unique (slip_id, line_no)
);

alter table public.store_order_lines
    drop constraint if exists store_order_lines_item_id_fkey;

alter table public.store_order_lines
    add column if not exists source_type text;

alter table public.store_order_lines
    add column if not exists source_id bigint;

alter table public.store_order_lines
    add column if not exists item_category_id_snapshot bigint;

alter table public.store_order_lines
    add column if not exists item_category_code_snapshot text;

alter table public.store_order_lines
    add column if not exists item_category_name_snapshot text;

-- 既存注文明細へ現在のカテゴリを一度だけ固定します。
-- 締め後ガード以外の監査時刻・営業中画面revisionトリガーは一時停止し、履歴値を変えません。
do $$
declare
    v_previous_setting text;
    v_updated_at_trigger "char";
    v_revision_trigger "char";
begin
    select t.tgenabled
      into v_updated_at_trigger
      from pg_trigger t
     where t.tgrelid = 'public.store_order_lines'::regclass
       and t.tgname = 'trg_store_order_lines_set_updated_at'
       and not t.tgisinternal;

    select t.tgenabled
      into v_revision_trigger
      from pg_trigger t
     where t.tgrelid = 'public.store_order_lines'::regclass
       and t.tgname = 'trg_store_order_lines_business_ui_revision'
       and not t.tgisinternal;

    if v_updated_at_trigger is not null then
        alter table public.store_order_lines disable trigger trg_store_order_lines_set_updated_at;
    end if;

    if v_revision_trigger is not null then
        alter table public.store_order_lines disable trigger trg_store_order_lines_business_ui_revision;
    end if;

    v_previous_setting := current_setting('store.allow_closed_day_mutation', true);
    perform set_config('store.allow_closed_day_mutation', 'on', true);

    update public.store_order_lines ol
       set item_category_id_snapshot = i.item_category_id,
           item_category_code_snapshot = c.category_code,
           item_category_name_snapshot = c.category_name
      from public.store_item_master i
      join public.store_item_category_master c
        on c.item_category_id = i.item_category_id
     where i.item_id = ol.item_id
       and ol.item_category_id_snapshot is null;

    perform set_config('store.allow_closed_day_mutation', coalesce(v_previous_setting, ''), true);

    if v_updated_at_trigger = 'O' then
        alter table public.store_order_lines enable trigger trg_store_order_lines_set_updated_at;
    elsif v_updated_at_trigger = 'R' then
        alter table public.store_order_lines enable replica trigger trg_store_order_lines_set_updated_at;
    elsif v_updated_at_trigger = 'A' then
        alter table public.store_order_lines enable always trigger trg_store_order_lines_set_updated_at;
    end if;

    if v_revision_trigger = 'O' then
        alter table public.store_order_lines enable trigger trg_store_order_lines_business_ui_revision;
    elsif v_revision_trigger = 'R' then
        alter table public.store_order_lines enable replica trigger trg_store_order_lines_business_ui_revision;
    elsif v_revision_trigger = 'A' then
        alter table public.store_order_lines enable always trigger trg_store_order_lines_business_ui_revision;
    end if;
end $$;

alter table public.store_order_lines
    drop constraint if exists chk_store_order_lines_source_type;

alter table public.store_order_lines
    add constraint chk_store_order_lines_source_type
    check (source_type is null or source_type in ('nomination_fee', 'automatic_pricing'));

do $$
declare
    v_nomination record;
    v_line_no integer;
begin
    for v_nomination in
        select
            s.slip_id,
            s.company_id,
            s.department_id,
            sc.slip_cast_id,
            sc.nomination_price,
            coalesce(sc.started_at, s.opened_at) as ordered_at,
            i.item_id,
            i.item_name
        from public.store_slip_casts sc
        join public.store_slips s
          on s.slip_id = sc.slip_id
        join public.store_item_master i
          on i.company_id = s.company_id
         and i.department_id = s.department_id
         and i.item_type = 'nomination_fee'
         and i.is_active = true
        where sc.status = 'active'
          and sc.nomination_price > 0
          and not exists (
              select 1
              from public.store_order_lines ol
              where ol.source_type = 'nomination_fee'
                and ol.source_id = sc.slip_cast_id
                and ol.status = 'active'
          )
    loop
        select coalesce(max(ol.line_no), 0) + 1
          into v_line_no
        from public.store_order_lines ol
        where ol.slip_id = v_nomination.slip_id;

        insert into public.store_order_lines (
            slip_id,
            line_no,
            item_id,
            item_name_snapshot,
            quantity,
            unit_price,
            amount,
            ordered_at,
            status,
            source_type,
            source_id
        )
        values (
            v_nomination.slip_id,
            v_line_no,
            v_nomination.item_id,
            v_nomination.item_name,
            1,
            v_nomination.nomination_price,
            v_nomination.nomination_price,
            v_nomination.ordered_at,
            'active',
            'nomination_fee',
            v_nomination.slip_cast_id
        );
    end loop;
end $$;

create table if not exists public.store_order_line_cast_backs (
    order_line_cast_back_id bigint generated by default as identity primary key,
    order_line_id bigint not null references public.store_order_lines(order_line_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    back_type text not null default 'drink',
    quantity numeric(10, 2) not null default 1,
    back_unit_amount numeric(12, 0) not null default 0,
    back_amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_order_line_cast_backs_type check (back_type in ('drink', 'sales', 'other')),
    constraint chk_store_order_line_cast_backs_quantity check (quantity > 0),
    constraint chk_store_order_line_cast_backs_unit_amount check (back_unit_amount >= 0),
    constraint chk_store_order_line_cast_backs_amount check (back_amount >= 0),
    constraint chk_store_order_line_cast_backs_status check (status in ('active', 'voided', 'cancelled'))
);

create table if not exists public.store_slip_cast_backs (
    slip_cast_back_id bigint generated by default as identity primary key,
    slip_cast_id bigint not null references public.store_slip_casts(slip_cast_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    nomination_kind text not null default 'nomination',
    nomination_type text not null,
    back_type text not null default 'nomination',
    quantity numeric(10, 2) not null default 1,
    back_unit_amount numeric(12, 0) not null default 0,
    back_amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_cast_backs_nomination_type check (nomination_type in ('nomination', 'in_store', 'companion')),
    constraint chk_store_slip_cast_backs_back_type check (back_type = 'nomination'),
    constraint chk_store_slip_cast_backs_quantity check (quantity > 0),
    constraint chk_store_slip_cast_backs_unit_amount check (back_unit_amount >= 0),
    constraint chk_store_slip_cast_backs_amount check (back_amount >= 0),
    constraint chk_store_slip_cast_backs_status check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_slip_cast_backs_slip_cast unique (slip_cast_id)
);

-- 締め作業で入力する、伝票に紐付かないシャンパン追加バックです。
-- 0円も保存し、当日の出勤キャスト全員の入力完了を判定できます。
create table if not exists public.store_business_day_champagne_backs (
    business_day_champagne_back_id bigint generated by default as identity primary key,
    business_day_id bigint not null references public.store_business_days(business_day_id),
    business_date date not null,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    back_type text not null default 'champagne',
    quantity numeric(10, 2) not null default 1,
    back_unit_amount numeric(12, 0) not null default 0,
    back_amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_business_day_champagne_backs_type check (back_type = 'champagne'),
    constraint chk_store_business_day_champagne_backs_quantity check (quantity = 1),
    constraint chk_store_business_day_champagne_backs_unit_amount check (back_unit_amount >= 0),
    constraint chk_store_business_day_champagne_backs_amount check (back_amount >= 0),
    constraint chk_store_business_day_champagne_backs_status check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_business_day_champagne_backs_day_cast unique (business_day_id, cast_id)
);

alter table public.store_slip_cast_backs
    add column if not exists nomination_kind text not null default 'nomination';

update public.store_slip_cast_backs b
   set nomination_kind = sc.nomination_kind
  from public.store_slip_casts sc
 where sc.slip_cast_id = b.slip_cast_id
   and b.nomination_kind = 'nomination'
   and sc.nomination_kind <> 'nomination';

create table if not exists public.store_slip_charge_lines (
    charge_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    line_no integer not null,
    charge_type text not null,
    line_name text not null,
    quantity numeric(10, 2) not null default 1,
    unit_price numeric(12, 0) not null default 0,
    amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_charge_lines_type check (charge_type in ('adjustment', 'karaoke')),
    constraint chk_store_slip_charge_lines_name check (length(trim(line_name)) > 0),
    constraint chk_store_slip_charge_lines_quantity check (quantity > 0),
    constraint chk_store_slip_charge_lines_adjustment check (charge_type <> 'adjustment' or quantity = 1),
    constraint chk_store_slip_charge_lines_karaoke check (charge_type <> 'karaoke' or (unit_price = 200 and amount >= 0)),
    constraint chk_store_slip_charge_lines_status check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_slip_charge_lines_line unique (slip_id, line_no)
);

do $$
declare
    v_charge record;
    v_order_line_id bigint;
    v_line_no integer;
    v_entered_at timestamp with time zone;
begin
    for v_charge in
        select
            s.slip_id,
            s.business_day_id,
            s.opened_at,
            i.item_id,
            i.item_name,
            i.default_price,
            sum(cl.quantity) as quantity
        from public.store_slip_charge_lines cl
        join public.store_slips s
          on s.slip_id = cl.slip_id
        join public.store_item_master i
          on i.company_id = cl.company_id
         and i.department_id = cl.department_id
         and i.item_type = 'karaoke'
         and i.is_active = true
        where cl.charge_type = 'karaoke'
          and cl.status = 'active'
        group by s.slip_id, s.business_day_id, s.opened_at, i.item_id, i.item_name, i.default_price
    loop
        select coalesce(min(c.entered_at), v_charge.opened_at)
          into v_entered_at
        from public.store_slip_customers c
        where c.slip_id = v_charge.slip_id
          and c.status <> 'cancelled';

        select ol.order_line_id
          into v_order_line_id
        from public.store_order_lines ol
        join public.store_item_master i
          on i.item_id = ol.item_id
        where ol.slip_id = v_charge.slip_id
          and ol.status = 'active'
          and i.item_type = 'karaoke'
        order by ol.line_no asc
        limit 1;

        update public.store_order_lines ol
           set status = 'voided',
               voided_at = coalesce(ol.voided_at, now()),
               updated_at = now()
        from public.store_item_master i
        where i.item_id = ol.item_id
          and ol.slip_id = v_charge.slip_id
          and ol.status = 'active'
          and i.item_type = 'karaoke'
          and (v_order_line_id is null or ol.order_line_id <> v_order_line_id);

        if v_order_line_id is null then
            select coalesce(max(ol.line_no), 0) + 1
              into v_line_no
            from public.store_order_lines ol
            where ol.slip_id = v_charge.slip_id;

            insert into public.store_order_lines (
                slip_id,
                line_no,
                item_id,
                item_name_snapshot,
                quantity,
                unit_price,
                amount,
                ordered_at,
                status
            )
            values (
                v_charge.slip_id,
                v_line_no,
                v_charge.item_id,
                v_charge.item_name,
                v_charge.quantity,
                v_charge.default_price,
                v_charge.default_price * v_charge.quantity,
                v_entered_at,
                'active'
            );
        else
            update public.store_order_lines ol
               set item_id = v_charge.item_id,
                   item_name_snapshot = v_charge.item_name,
                   quantity = v_charge.quantity,
                   unit_price = v_charge.default_price,
                   amount = v_charge.default_price * v_charge.quantity,
                   ordered_at = v_entered_at,
                   status = 'active',
                   voided_at = null,
                   updated_at = now()
             where ol.order_line_id = v_order_line_id;
        end if;
    end loop;

    update public.store_slip_charge_lines cl
       set status = 'voided',
           updated_at = now()
     where cl.charge_type = 'karaoke'
       and cl.status = 'active';
end $$;

create table if not exists public.store_checkouts (
    checkout_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    checkout_at timestamp with time zone not null,
    total_amount numeric(12, 0) not null default 0,
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    received_amount numeric(12, 0),
    change_amount numeric(12, 0),
    status text not null default 'draft',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_checkouts_total_amount check (total_amount >= 0),
    constraint chk_store_checkouts_received_amount check (received_amount is null or received_amount >= 0),
    constraint chk_store_checkouts_change_amount check (change_amount is null or change_amount >= 0),
    constraint chk_store_checkouts_status check (status in ('draft', 'confirmed', 'cancelled'))
);

alter table public.store_checkouts
    add column if not exists subtotal_amount numeric(12, 0) not null default 0;

alter table public.store_checkouts
    add column if not exists service_tax_amount numeric(12, 0) not null default 0;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'store_checkouts'
          and column_name = 'service_tax_amount'
    ) and not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'store_checkouts'
          and column_name = 'service_charge_amount'
    ) then
        alter table public.store_checkouts
            rename column service_tax_amount to service_charge_amount;
    end if;
end $$;

alter table public.store_checkouts
    add column if not exists service_charge_amount numeric(12, 0) not null default 0;

alter table public.store_checkouts
    add column if not exists issuer_snapshot jsonb not null default '{}'::jsonb;

alter table public.company_master
    add column if not exists invoice_registration_number text;

alter table public.department_master
    add column if not exists receipt_display_name text;

alter table public.department_master
    add column if not exists receipt_address text;

alter table public.department_master
    add column if not exists receipt_phone text;

alter table public.department_master
    add column if not exists receipt_logo text;

update public.company_master
   set invoice_registration_number = coalesce(nullif(trim(invoice_registration_number), ''), 'T1234567890123')
 where invoice_registration_number is null
    or trim(invoice_registration_number) = '';

update public.department_master
   set receipt_display_name = coalesce(nullif(trim(receipt_display_name), ''), '【テスト店舗】'),
       receipt_address = coalesce(nullif(trim(receipt_address), ''), '東京都テスト区テスト1-2-3'),
       receipt_phone = coalesce(nullif(trim(receipt_phone), ''), '00-1234-5678'),
       receipt_logo = coalesce(nullif(trim(receipt_logo), ''), '【テストロゴ】')
 where receipt_display_name is null or trim(receipt_display_name) = ''
    or receipt_address is null or trim(receipt_address) = ''
    or receipt_phone is null or trim(receipt_phone) = ''
    or receipt_logo is null or trim(receipt_logo) = '';

insert into public.payment_method_master (
    company_id,
    department_id,
    payment_method_code,
    payment_method_name,
    requires_received_amount,
    sort_order,
    is_active
)
select
    d.company_id,
    d.department_id,
    v.payment_method_code,
    v.payment_method_name,
    v.requires_received_amount,
    v.sort_order,
    true
from public.department_master d
cross join (
    values
        ('cash'::text, '現金'::text, true, 10),
        ('cat'::text, 'CAT'::text, false, 20),
        ('paypay'::text, 'PAYPAY'::text, false, 30)
) as v(payment_method_code, payment_method_name, requires_received_amount, sort_order)
where d.is_active = true
on conflict (company_id, department_id, payment_method_code)
do update set
    payment_method_name = excluded.payment_method_name,
    requires_received_amount = excluded.requires_received_amount,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

alter table public.store_checkouts
    drop constraint if exists uq_store_checkouts_slip;

create unique index if not exists ux_store_checkouts_active_slip
    on public.store_checkouts(slip_id)
    where status <> 'cancelled';

create table if not exists public.store_checkout_payments (
    checkout_payment_id bigint generated by default as identity primary key,
    checkout_id bigint not null references public.store_checkouts(checkout_id) on delete cascade,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    payment_method_id bigint references public.payment_method_master(payment_method_id),
    payment_method_code text not null,
    payment_method_name text not null,
    amount numeric(12, 0) not null default 0,
    status text not null default 'confirmed',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_checkout_payments_amount check (amount >= 0),
    constraint chk_store_checkout_payments_status check (status in ('confirmed', 'cancelled'))
);

create table if not exists public.store_slip_cast_sales_adjustments (
    adjustment_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    checkout_id bigint not null references public.store_checkouts(checkout_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    slip_cast_id bigint not null references public.store_slip_casts(slip_cast_id) on delete cascade,
    cast_id bigint not null references public.cast_master(cast_id),
    source_amount_type text not null default 'total',
    split_mode text not null default 'split',
    base_amount numeric(12, 0) not null default 0,
    sales_amount numeric(12, 0) not null default 0,
    status text not null default 'confirmed',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_cast_sales_adjustments_source check (source_amount_type in ('subtotal', 'total')),
    constraint chk_store_slip_cast_sales_adjustments_split check (split_mode in ('split', 'full')),
    constraint chk_store_slip_cast_sales_adjustments_base_amount check (base_amount >= 0),
    constraint chk_store_slip_cast_sales_adjustments_sales_amount check (sales_amount >= 0),
    constraint chk_store_slip_cast_sales_adjustments_status check (status in ('confirmed', 'cancelled'))
);

-- 会計伝票出力時点の表示・計算結果を版管理します。
-- cast_id / department_id は集計軸として元テーブルに保持し、帳票・画面表示はこの固定値を使います。
create table if not exists public.store_slip_accounting_snapshots (
    accounting_snapshot_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint not null references public.store_business_days(business_day_id),
    business_date date not null,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    snapshot_version integer not null,
    status text not null default 'active',
    invalidation_reason text,
    checkout_ready_at timestamp with time zone not null,
    invalidated_at timestamp with time zone,
    print_data jsonb not null,
    review_data jsonb not null,
    business_home_data jsonb not null,
    backfilled boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint uq_store_slip_accounting_snapshot_version unique (slip_id, snapshot_version),
    constraint chk_store_slip_accounting_snapshot_version check (snapshot_version >= 1),
    constraint chk_store_slip_accounting_snapshot_status check (status in ('active', 'released', 'cancelled')),
    constraint chk_store_slip_accounting_snapshot_invalidation check (
        (status = 'active' and invalidated_at is null and invalidation_reason is null) or
        (status <> 'active' and invalidated_at is not null and length(trim(invalidation_reason)) > 0)
    ),
    constraint chk_store_slip_accounting_snapshot_payload check (
        jsonb_typeof(print_data) = 'object' and
        jsonb_typeof(review_data) = 'object' and
        jsonb_typeof(business_home_data) = 'object'
    )
);

create unique index if not exists ux_store_slip_accounting_snapshots_active
    on public.store_slip_accounting_snapshots(slip_id)
    where status = 'active';

alter table public.store_slip_accounting_snapshots
    add column if not exists backfilled boolean not null default false;

create index if not exists idx_store_slip_accounting_snapshots_day
    on public.store_slip_accounting_snapshots(department_id, business_day_id, status);

-- 営業日締めと同じトランザクションで作る日次正本です。
-- 既存締め日の移行時だけ backfilled=true とし、その時点を将来変更に対する基準値にします。
create table if not exists public.store_business_day_closing_snapshots (
    closing_snapshot_id bigint generated by default as identity primary key,
    business_day_id bigint not null references public.store_business_days(business_day_id),
    business_date date not null,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    snapshot_version integer not null default 1,
    closed_at timestamp with time zone not null,
    backfilled boolean not null default false,
    business_home_data jsonb not null,
    closing_data jsonb not null,
    created_at timestamp with time zone not null default now(),
    constraint uq_store_business_day_closing_snapshot_version unique (business_day_id, snapshot_version),
    constraint chk_store_business_day_closing_snapshot_version check (snapshot_version >= 1),
    constraint chk_store_business_day_closing_snapshot_payload check (
        jsonb_typeof(business_home_data) = 'object' and
        jsonb_typeof(closing_data) = 'object'
    )
);

create unique index if not exists ux_store_business_day_closing_snapshots_day
    on public.store_business_day_closing_snapshots(business_day_id);

create index if not exists idx_store_business_day_closing_snapshots_lookup
    on public.store_business_day_closing_snapshots(department_id, business_date desc);

create index if not exists idx_store_table_master_active
    on public.store_table_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_cast_master_active
    on public.cast_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_store_item_category_master_active
    on public.store_item_category_master(company_id, department_id, is_active, sort_order);

create index if not exists idx_store_item_master_active
    on public.store_item_master(company_id, department_id, is_active, sort_order);

create unique index if not exists ux_store_item_master_karaoke_active
    on public.store_item_master(company_id, department_id)
    where item_type = 'karaoke' and is_active = true;

create unique index if not exists ux_store_item_master_nomination_fee_active
    on public.store_item_master(company_id, department_id)
    where item_type = 'nomination_fee' and is_active = true;

create unique index if not exists ux_store_item_master_set_fee_active
    on public.store_item_master(company_id, department_id)
    where item_type = 'set_fee' and is_active = true;

create unique index if not exists ux_store_item_master_extension_fee_active
    on public.store_item_master(company_id, department_id)
    where item_type = 'extension_fee' and is_active = true;

create index if not exists idx_payment_method_master_active
    on public.payment_method_master(company_id, department_id, is_active, sort_order);

create unique index if not exists ux_store_business_days_one_open
    on public.store_business_days(company_id, department_id)
    where status = 'open';

create index if not exists idx_store_business_days_lookup
    on public.store_business_days(company_id, department_id, business_date, status);

create index if not exists idx_store_business_days_open_department
    on public.store_business_days(department_id, opened_at desc)
    where status = 'open';

create index if not exists idx_store_cast_attendance_day_status
    on public.store_cast_attendance(company_id, department_id, business_day_id, attendance_status);

create index if not exists idx_store_cast_attendance_department_day_status
    on public.store_cast_attendance(department_id, business_day_id, attendance_status, cast_id);

create index if not exists idx_store_cast_attendance_cast
    on public.store_cast_attendance(cast_id, business_date);

create index if not exists idx_store_slips_open
    on public.store_slips(company_id, department_id, status, opened_at);

create index if not exists idx_store_slips_business_day
    on public.store_slips(business_day_id, status);

create index if not exists idx_store_slips_department_business_day
    on public.store_slips(department_id, business_day_id, opened_at);

create index if not exists idx_store_slip_customers_slip_status
    on public.store_slip_customers(slip_id, status);

create index if not exists idx_store_slip_casts_slip
    on public.store_slip_casts(slip_id);

create index if not exists idx_store_order_lines_slip_status
    on public.store_order_lines(slip_id, status);

create unique index if not exists ux_store_order_lines_active_source
    on public.store_order_lines(source_type, source_id)
    where source_type is not null and status = 'active';

create index if not exists idx_store_order_line_cast_backs_cast_date
    on public.store_order_line_cast_backs(company_id, department_id, cast_id, business_date, status);

create index if not exists idx_store_order_line_cast_backs_line
    on public.store_order_line_cast_backs(order_line_id, status);

create index if not exists idx_store_nomination_back_master_department
    on public.store_nomination_back_master(department_id, is_active, sort_order);

create index if not exists idx_store_slip_cast_backs_cast_date
    on public.store_slip_cast_backs(company_id, department_id, cast_id, business_date, status);

create index if not exists idx_store_slip_cast_backs_slip
    on public.store_slip_cast_backs(slip_id, status);

create index if not exists idx_store_slip_cast_backs_slip_cast
    on public.store_slip_cast_backs(slip_cast_id, status);

create index if not exists idx_store_business_day_champagne_backs_cast_date
    on public.store_business_day_champagne_backs(company_id, department_id, cast_id, business_date, status);

create index if not exists idx_store_business_day_champagne_backs_day
    on public.store_business_day_champagne_backs(department_id, business_day_id, status);

create index if not exists idx_store_slip_charge_lines_slip_status
    on public.store_slip_charge_lines(slip_id, charge_type, status);

create index if not exists idx_store_slip_charge_lines_day
    on public.store_slip_charge_lines(company_id, department_id, business_day_id, status);

create index if not exists idx_store_checkouts_date
    on public.store_checkouts(company_id, department_id, checkout_at);

create index if not exists idx_store_checkouts_slip_status
    on public.store_checkouts(slip_id, status);

create index if not exists idx_store_checkout_payments_checkout
    on public.store_checkout_payments(checkout_id, status);

create index if not exists idx_store_slip_cast_sales_adjustments_day
    on public.store_slip_cast_sales_adjustments(company_id, department_id, business_day_id, status);

alter table public.store_slip_cast_sales_adjustments
    drop constraint if exists uq_store_slip_cast_sales_adjustments_slip_cast;

create unique index if not exists ux_store_slip_cast_sales_adjustments_confirmed
    on public.store_slip_cast_sales_adjustments(slip_id, slip_cast_id)
    where status = 'confirmed';

create index if not exists idx_store_slip_cast_sales_adjustments_slip
    on public.store_slip_cast_sales_adjustments(slip_id, status);

create index if not exists idx_store_slip_cast_sales_adjustments_cast_date
    on public.store_slip_cast_sales_adjustments(company_id, department_id, cast_id, business_date, status);

alter table public.store_table_master enable row level security;
alter table public.cast_master enable row level security;
alter table public.store_item_category_master enable row level security;
alter table public.store_item_master enable row level security;
alter table public.store_nomination_back_master enable row level security;
alter table public.payment_method_master enable row level security;
alter table public.store_business_days enable row level security;
alter table public.store_cast_attendance enable row level security;
alter table public.store_slips enable row level security;
alter table public.store_slip_customers enable row level security;
alter table public.store_slip_casts enable row level security;
alter table public.store_order_lines enable row level security;
alter table public.store_order_line_cast_backs enable row level security;
alter table public.store_slip_cast_backs enable row level security;
alter table public.store_business_day_champagne_backs enable row level security;
alter table public.store_slip_charge_lines enable row level security;
alter table public.store_checkouts enable row level security;
alter table public.store_checkout_payments enable row level security;
alter table public.store_slip_cast_sales_adjustments enable row level security;
alter table public.store_slip_accounting_snapshots enable row level security;
alter table public.store_business_day_closing_snapshots enable row level security;

drop trigger if exists trg_store_table_master_set_updated_at on public.store_table_master;
create trigger trg_store_table_master_set_updated_at
before update on public.store_table_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_cast_master_set_updated_at on public.cast_master;
create trigger trg_cast_master_set_updated_at
before update on public.cast_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_item_category_master_set_updated_at on public.store_item_category_master;
create trigger trg_store_item_category_master_set_updated_at
before update on public.store_item_category_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_item_master_set_updated_at on public.store_item_master;
create trigger trg_store_item_master_set_updated_at
before update on public.store_item_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_nomination_back_master_set_updated_at on public.store_nomination_back_master;
create trigger trg_store_nomination_back_master_set_updated_at
before update on public.store_nomination_back_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_payment_method_master_set_updated_at on public.payment_method_master;
create trigger trg_payment_method_master_set_updated_at
before update on public.payment_method_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_business_days_set_updated_at on public.store_business_days;
create trigger trg_store_business_days_set_updated_at
before update on public.store_business_days
for each row execute function public.set_updated_at();

-- 営業中トップが古い全伝票スナップショットで新しい状態を上書きしないため、
-- 伝票に属する更新ごとに営業日単位の単調増加番号を進めます。
create or replace function public.bump_store_business_day_ui_revision_from_slip()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    v_slip_id bigint;
    v_business_day_id bigint;
begin
    if tg_table_name = 'store_slips' then
        v_business_day_id := case when tg_op = 'DELETE' then old.business_day_id else new.business_day_id end;
    elsif tg_table_name = 'store_order_line_cast_backs' then
        select ol.slip_id
          into v_slip_id
        from public.store_order_lines ol
        where ol.order_line_id = case when tg_op = 'DELETE' then old.order_line_id else new.order_line_id end;
    else
        v_slip_id := case when tg_op = 'DELETE' then old.slip_id else new.slip_id end;
    end if;

    if v_slip_id is not null then
        select s.business_day_id
          into v_business_day_id
        from public.store_slips s
        where s.slip_id = v_slip_id;
    end if;

    if v_business_day_id is not null then
        update public.store_business_days b
           set business_ui_revision = b.business_ui_revision + 1
         where b.business_day_id = v_business_day_id;
    end if;

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

create or replace function public.snapshot_store_order_line_item_category()
returns trigger
language plpgsql
set search_path = public
as $$
declare
    v_item_category_id bigint;
    v_category_code text;
    v_category_name text;
begin
    if tg_op = 'UPDATE' and new.item_id is not distinct from old.item_id then
        return new;
    end if;

    if new.item_id is null then
        if tg_op = 'UPDATE' then
            new.item_category_id_snapshot := null;
            new.item_category_code_snapshot := null;
            new.item_category_name_snapshot := null;
        end if;
        return new;
    end if;

    select i.item_category_id, c.category_code, c.category_name
      into v_item_category_id, v_category_code, v_category_name
      from public.store_item_master i
      left join public.store_item_category_master c
        on c.item_category_id = i.item_category_id
     where i.item_id = new.item_id;

    if found then
        new.item_category_id_snapshot := v_item_category_id;
        new.item_category_code_snapshot := v_category_code;
        new.item_category_name_snapshot := v_category_name;
    elsif tg_op = 'UPDATE' then
        new.item_category_id_snapshot := null;
        new.item_category_code_snapshot := null;
        new.item_category_name_snapshot := null;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_store_order_lines_item_category_snapshot on public.store_order_lines;
create trigger trg_store_order_lines_item_category_snapshot
before insert or update of item_id on public.store_order_lines
for each row execute function public.snapshot_store_order_line_item_category();

drop trigger if exists trg_store_slips_business_ui_revision on public.store_slips;
create trigger trg_store_slips_business_ui_revision
after insert or update or delete on public.store_slips
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop trigger if exists trg_store_slip_customers_business_ui_revision on public.store_slip_customers;
create trigger trg_store_slip_customers_business_ui_revision
after insert or update or delete on public.store_slip_customers
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop trigger if exists trg_store_slip_casts_business_ui_revision on public.store_slip_casts;
create trigger trg_store_slip_casts_business_ui_revision
after insert or update or delete on public.store_slip_casts
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop trigger if exists trg_store_order_lines_business_ui_revision on public.store_order_lines;
create trigger trg_store_order_lines_business_ui_revision
after insert or update or delete on public.store_order_lines
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop trigger if exists trg_store_order_line_cast_backs_business_ui_revision on public.store_order_line_cast_backs;
create trigger trg_store_order_line_cast_backs_business_ui_revision
after insert or update or delete on public.store_order_line_cast_backs
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop trigger if exists trg_store_slip_charge_lines_business_ui_revision on public.store_slip_charge_lines;
create trigger trg_store_slip_charge_lines_business_ui_revision
after insert or update or delete on public.store_slip_charge_lines
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop trigger if exists trg_store_cast_attendance_set_updated_at on public.store_cast_attendance;
create trigger trg_store_cast_attendance_set_updated_at
before update on public.store_cast_attendance
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slips_set_updated_at on public.store_slips;
create trigger trg_store_slips_set_updated_at
before update on public.store_slips
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_customers_set_updated_at on public.store_slip_customers;
create trigger trg_store_slip_customers_set_updated_at
before update on public.store_slip_customers
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_casts_set_updated_at on public.store_slip_casts;
create trigger trg_store_slip_casts_set_updated_at
before update on public.store_slip_casts
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_order_lines_set_updated_at on public.store_order_lines;
create trigger trg_store_order_lines_set_updated_at
before update on public.store_order_lines
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_order_line_cast_backs_set_updated_at on public.store_order_line_cast_backs;
create trigger trg_store_order_line_cast_backs_set_updated_at
before update on public.store_order_line_cast_backs
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_cast_backs_set_updated_at on public.store_slip_cast_backs;
create trigger trg_store_slip_cast_backs_set_updated_at
before update on public.store_slip_cast_backs
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_business_day_champagne_backs_set_updated_at on public.store_business_day_champagne_backs;
create trigger trg_store_business_day_champagne_backs_set_updated_at
before update on public.store_business_day_champagne_backs
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_charge_lines_set_updated_at on public.store_slip_charge_lines;
create trigger trg_store_slip_charge_lines_set_updated_at
before update on public.store_slip_charge_lines
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_checkouts_set_updated_at on public.store_checkouts;
create trigger trg_store_checkouts_set_updated_at
before update on public.store_checkouts
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_checkout_payments_set_updated_at on public.store_checkout_payments;
create trigger trg_store_checkout_payments_set_updated_at
before update on public.store_checkout_payments
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_cast_sales_adjustments_set_updated_at on public.store_slip_cast_sales_adjustments;
create trigger trg_store_slip_cast_sales_adjustments_set_updated_at
before update on public.store_slip_cast_sales_adjustments
for each row execute function public.set_updated_at();

commit;
