-- 旧シャンパンバック物理モデルを新ドリンクバック調整へ一方向移行します。

begin;

drop function if exists store.get_business_day_champagne_back_status(bigint, bigint);
drop function if exists store.get_business_day_champagne_back_overview(bigint, bigint);
drop function if exists store.save_business_day_champagne_backs(bigint, bigint, jsonb);
drop function if exists public.get_business_day_champagne_back_status(bigint, bigint);
drop function if exists public.get_business_day_champagne_back_overview(bigint, bigint);
drop function if exists public.save_business_day_champagne_backs(bigint, bigint, jsonb);

create table if not exists public.store_business_day_drink_back_adjustments (
    business_day_drink_back_adjustment_id bigint generated by default as identity primary key,
    business_day_id bigint not null references public.store_business_days(business_day_id),
    business_date date not null,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    cast_id bigint not null references public.cast_master(cast_id),
    adjustment_amount numeric(12, 0) not null default 0,
    status text not null default 'active',
    memo text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_business_day_drink_back_adjustments_amount
        check (adjustment_amount between -999999999999 and 999999999999),
    constraint chk_store_business_day_drink_back_adjustments_status
        check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_business_day_drink_back_adjustments_day_cast
        unique (business_day_id, cast_id)
);

do $$
begin
    if to_regclass('public.store_business_day_champagne_backs') is not null then
        execute $migration$
            insert into public.store_business_day_drink_back_adjustments (
                business_day_id,
                business_date,
                company_id,
                department_id,
                cast_id,
                adjustment_amount,
                status,
                memo,
                created_at,
                updated_at
            )
            select
                legacy.business_day_id,
                legacy.business_date,
                legacy.company_id,
                legacy.department_id,
                legacy.cast_id,
                legacy.back_amount,
                legacy.status,
                legacy.memo,
                legacy.created_at,
                legacy.updated_at
            from public.store_business_day_champagne_backs legacy
            on conflict (business_day_id, cast_id) do update
                set business_date = excluded.business_date,
                    company_id = excluded.company_id,
                    department_id = excluded.department_id,
                    adjustment_amount = excluded.adjustment_amount,
                    status = excluded.status,
                    memo = excluded.memo,
                    created_at = excluded.created_at,
                    updated_at = excluded.updated_at
        $migration$;

        execute 'drop table public.store_business_day_champagne_backs';
    end if;
end;
$$;

create index if not exists idx_store_business_day_drink_back_adjustments_cast_date
    on public.store_business_day_drink_back_adjustments(company_id, department_id, cast_id, business_date, status);
create index if not exists idx_store_business_day_drink_back_adjustments_day
    on public.store_business_day_drink_back_adjustments(department_id, business_day_id, status);
create index if not exists idx_store_business_day_drink_back_adjustments_cast
    on public.store_business_day_drink_back_adjustments(cast_id);
alter table public.store_business_day_drink_back_adjustments enable row level security;
revoke all on table public.store_business_day_drink_back_adjustments
    from public, anon, authenticated, service_role;

commit;
