begin;

drop function if exists store.quick_enter_receipt(bigint, text, date, numeric, text, text, text, text);
drop function if exists store.quick_enter_receipt(bigint, text, date, numeric, text, text, text, jsonb, text);
drop function if exists store.quick_enter_receipt(bigint, text, date, numeric, text, text, text, jsonb, text, bigint, bigint);
drop function if exists store.mark_receipt_scan_mistake(bigint, text, text);
drop function if exists store.get_pending_receipts(bigint, text);

create table if not exists public.store_business_day_receipt_expenses (
    receipt_expense_id bigint generated by default as identity primary key,
    business_day_id bigint not null references public.store_business_days(business_day_id) on delete cascade,
    business_date date not null,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    document_id text not null,
    journal_entry_id uuid not null references accounting.journal_entries(journal_entry_id),
    transaction_date date not null,
    account_subject text not null,
    amount numeric(12, 0) not null,
    memo text,
    created_at timestamp with time zone not null default now(),
    constraint chk_store_business_day_receipt_expenses_amount check (amount > 0),
    constraint uq_store_business_day_receipt_expenses_document unique (document_id),
    constraint uq_store_business_day_receipt_expenses_journal unique (journal_entry_id)
);

create index if not exists idx_store_business_day_receipt_expenses_day
    on public.store_business_day_receipt_expenses(department_id, business_day_id);

create index if not exists idx_store_business_day_receipt_expenses_company
    on public.store_business_day_receipt_expenses(company_id);

alter table public.store_business_day_receipt_expenses enable row level security;
revoke all on table public.store_business_day_receipt_expenses from public, anon, authenticated, service_role;

create or replace function store.get_pending_receipts_internal(
    p_department_id bigint,
    p_status text default 'unprocessed'
)
returns table (
    document_id text,
    file_id bigint,
    document_date date,
    amount numeric,
    status text,
    file_name text,
    drive_file_id text,
    drive_url text,
    storage_path text
)
language sql
security definer
set search_path = pg_catalog, public
as $$
    with department as (
        select d.department_id, d.company_id
        from public.department_master d
        where d.department_id = p_department_id
          and d.is_active = true
    ),
    document_status as (
        select
            d.document_id,
            case
                when count(link.link_id) = 0 then 'unlinked'
                when bool_or(entry.status = 'draft') then 'draft'
                when bool_or(entry.status = 'confirmed') then 'confirmed'
                when bool_or(entry.status = 'exported') then 'exported'
                when bool_or(entry.status = 'voided') then 'voided'
                else 'linked'
            end as link_status
        from accounting.documents d
        left join accounting.document_journal_links link
          on link.document_id = d.document_id
        left join accounting.journal_entries entry
          on entry.journal_entry_id = link.journal_entry_id
        where d.deleted_at is null
        group by d.document_id
    )
    select
        document.document_id,
        null::bigint as file_id,
        draft_entry.entry_date as document_date,
        draft_entry.amount,
        case document_status.link_status
            when 'unlinked' then 'unprocessed'
            when 'confirmed' then 'quick_entered'
            when 'voided' then 'excluded'
            else document_status.link_status
        end as status,
        document.original_file_name as file_name,
        document.drive_file_id,
        document.drive_url,
        document.storage_path
    from accounting.documents document
    join document_status
      on document_status.document_id = document.document_id
    join department
      on department.company_id = document.company_id
    left join accounting.upload_source_master upload_source
      on upload_source.upload_source_id = document.upload_source_id
    left join lateral (
        select
            entry.entry_date,
            (
                select sum(line.amount)
                from accounting.journal_entry_lines line
                where line.journal_entry_id = entry.journal_entry_id
                  and line.dc_flag = 'D'
            ) as amount
        from accounting.document_journal_links link
        join accounting.journal_entries entry
          on entry.journal_entry_id = link.journal_entry_id
        where link.document_id = document.document_id
          and entry.status = 'draft'
        order by entry.updated_at desc, entry.journal_entry_id
        limit 1
    ) draft_entry on true
    where document.deleted_at is null
      and (
          upload_source.default_department_id = p_department_id
          or exists (
              select 1
              from accounting.document_journal_links link
              join accounting.journal_entry_lines line
                on line.journal_entry_id = link.journal_entry_id
              where link.document_id = document.document_id
                and line.department_id = p_department_id
          )
      )
      and case lower(coalesce(nullif(trim(p_status), ''), 'unprocessed'))
          when 'unprocessed' then document_status.link_status = 'unlinked'
          when 'quick_entered' then document_status.link_status = 'confirmed'
          when 'excluded' then document_status.link_status = 'voided'
          else document_status.link_status = lower(trim(p_status))
      end
    order by document.uploaded_at asc, document.file_no asc, document.document_id asc;
$$;

create or replace function store.quick_enter_receipt_internal(
    p_department_id bigint,
    p_document_id text,
    p_payment_date date,
    p_amount numeric,
    p_account_subject text,
    p_description text,
    p_group_code text,
    p_journal_payload jsonb default null,
    p_status text default 'quick_entered',
    p_business_day_id bigint default null,
    p_advance_cast_id bigint default null
)
returns table (
    document_id text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    v_company_id bigint;
    v_entry_id text;
    v_save_result jsonb;
    v_business_day public.store_business_days%rowtype;
    v_is_cast_advance boolean;
begin
    if nullif(trim(coalesce(p_document_id, '')), '') is null
       or p_payment_date is null
       or coalesce(p_amount, 0) <= 0
       or nullif(trim(coalesce(p_account_subject, '')), '') is null
       or nullif(trim(coalesce(p_description, '')), '') is null then
        raise exception 'invalid_receipt_input';
    end if;

    if lower(coalesce(nullif(trim(p_status), ''), 'quick_entered')) <> 'quick_entered' then
        raise exception 'invalid_receipt_status';
    end if;

    v_is_cast_advance := trim(p_account_subject) in ('前渡金: キャスト', '前渡金：キャスト');
    if trunc(p_amount) <> p_amount then
        raise exception 'receipt_amount_must_be_integer';
    end if;

    select department.company_id
      into v_company_id
    from public.department_master department
    where department.department_id = p_department_id
      and department.is_active = true;

    if v_company_id is null then
        raise exception 'store_department_not_found';
    end if;

    if coalesce(p_business_day_id, 0) <= 0 then
        raise exception 'receipt_reimbursement_business_day_required';
    end if;

    select business_day.*
      into v_business_day
      from public.store_business_days business_day
     where business_day.business_day_id = p_business_day_id
       and business_day.department_id = p_department_id
       and business_day.company_id = v_company_id
       and business_day.status = 'open'
     for update;

    if v_business_day.business_day_id is null then
        raise exception 'receipt_reimbursement_business_day_not_open';
    end if;

    if v_is_cast_advance then
        if coalesce(p_advance_cast_id, 0) <= 0 then
            raise exception 'cast_advance_attendance_required';
        end if;

        if not exists (
            select 1
              from public.store_cast_attendance attendance
              join public.cast_master cast_member
                on cast_member.cast_id = attendance.cast_id
             where attendance.business_day_id = p_business_day_id
               and attendance.department_id = p_department_id
               and attendance.cast_id = p_advance_cast_id
               and attendance.attendance_status in ('scheduled', 'checked_in', 'checked_out')
               and cast_member.company_id = v_company_id
               and cast_member.is_active = true
        ) then
            raise exception 'cast_advance_attending_cast_required';
        end if;
    elsif p_advance_cast_id is not null then
        raise exception 'unexpected_cast_advance_selection';
    end if;

    if not exists (
        select 1
        from accounting.documents document
        left join accounting.upload_source_master upload_source
          on upload_source.upload_source_id = document.upload_source_id
        where document.document_id = trim(p_document_id)
          and document.company_id = v_company_id
          and document.deleted_at is null
          and upload_source.default_department_id = p_department_id
          and not exists (
              select 1
              from accounting.document_journal_links link
              where link.document_id = document.document_id
          )
    ) then
        raise exception 'pending_receipt_not_found';
    end if;

    if p_journal_payload is null
       or jsonb_typeof(p_journal_payload) <> 'object'
       or jsonb_typeof(p_journal_payload->'journal_entries') <> 'array'
       or jsonb_array_length(p_journal_payload->'journal_entries') <> 1
       or jsonb_typeof(p_journal_payload->'journal_entry_lines') <> 'array'
       or jsonb_array_length(p_journal_payload->'journal_entry_lines') <> 2
       or jsonb_typeof(p_journal_payload->'document_journal_links') <> 'array'
       or jsonb_array_length(p_journal_payload->'document_journal_links') <> 1 then
        raise exception 'invalid_receipt_journal_payload';
    end if;

    v_entry_id := p_journal_payload->'journal_entries'->0->>'journal_entry_id';
    if nullif(trim(coalesce(v_entry_id, '')), '') is null
       or v_entry_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
       or p_journal_payload->'journal_entries'->0->>'journal_date' <> p_payment_date::text
       or lower(coalesce(
           nullif(trim(p_journal_payload->'journal_entries'->0->>'status'), ''),
           'confirmed'
       )) not in ('confirmed', 'ready') then
        raise exception 'invalid_receipt_journal_payload';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(p_journal_payload->'journal_entry_lines') line
        where line->>'journal_entry_id' <> v_entry_id
           or coalesce(nullif(line->>'company_id', '')::bigint, v_company_id) <> v_company_id
           or (
               nullif(line->>'department_id', '') is not null
               and (line->>'department_id')::bigint <> p_department_id
           )
    ) or exists (
        select 1
        from jsonb_array_elements(p_journal_payload->'document_journal_links') link
        where link->>'journal_entry_id' <> v_entry_id
           or link->>'document_id' <> trim(p_document_id)
    ) then
        raise exception 'receipt_journal_scope_mismatch';
    end if;

    if (
        select coalesce(sum(
            case when upper(line->>'side') in ('DEBIT', 'D')
                 then coalesce(nullif(line->>'amount', '')::numeric, 0)
                 else 0
            end
        ), 0)
        from jsonb_array_elements(p_journal_payload->'journal_entry_lines') line
    ) <> p_amount or (
        select coalesce(sum(
            case when upper(line->>'side') in ('CREDIT', 'C')
                 then coalesce(nullif(line->>'amount', '')::numeric, 0)
                 else 0
            end
        ), 0)
        from jsonb_array_elements(p_journal_payload->'journal_entry_lines') line
    ) <> p_amount then
        raise exception 'receipt_journal_amount_mismatch';
    end if;

    if v_is_cast_advance and not exists (
        select 1
          from jsonb_array_elements(p_journal_payload->'journal_entry_lines') line
         where upper(line->>'side') in ('DEBIT', 'D')
           and trim(line->>'account_code') = '前渡金'
           and coalesce(nullif(line->>'amount', '')::numeric, 0) = p_amount
    ) then
        raise exception 'cast_advance_journal_account_mismatch';
    end if;

    select accounting.save_journal_payload(p_journal_payload)
      into v_save_result;

    if coalesce((v_save_result->>'documents')::integer, 0) <> 1
       or coalesce((v_save_result->>'journal_entries')::integer, 0) <> 1
       or coalesce((v_save_result->>'journal_entry_lines')::integer, 0) <> 2
       or coalesce((v_save_result->>'document_journal_links')::integer, 0) <> 1 then
        raise exception 'receipt_journal_save_incomplete';
    end if;

    insert into public.store_business_day_receipt_expenses (
        business_day_id,
        business_date,
        company_id,
        department_id,
        document_id,
        journal_entry_id,
        transaction_date,
        account_subject,
        amount,
        memo
    )
    values (
        v_business_day.business_day_id,
        v_business_day.business_date,
        v_business_day.company_id,
        v_business_day.department_id,
        trim(p_document_id),
        v_entry_id::uuid,
        p_payment_date,
        trim(p_account_subject),
        p_amount,
        trim(p_description)
    );

    if v_is_cast_advance then
        insert into public.store_business_day_cast_advances (
            business_day_id,
            business_date,
            company_id,
            department_id,
            cast_id,
            journal_entry_id,
            amount,
            memo
        )
        values (
            v_business_day.business_day_id,
            v_business_day.business_date,
            v_business_day.company_id,
            v_business_day.department_id,
            p_advance_cast_id,
            v_entry_id::uuid,
            p_amount,
            trim(p_description)
        );
    end if;

    return query select trim(p_document_id);
end;
$$;

create or replace function store.mark_receipt_scan_mistake_internal(
    p_department_id bigint,
    p_document_id text,
    p_status text default 'excluded'
)
returns table (
    document_id text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    v_company_id bigint;
begin
    if nullif(trim(coalesce(p_document_id, '')), '') is null
       or lower(coalesce(nullif(trim(p_status), ''), 'excluded')) <> 'excluded' then
        raise exception 'invalid_receipt_exclusion';
    end if;

    select department.company_id
      into v_company_id
    from public.department_master department
    where department.department_id = p_department_id
      and department.is_active = true;

    if v_company_id is null then
        raise exception 'store_department_not_found';
    end if;

    return query
    update accounting.documents document
       set deleted_at = now(),
           updated_at = now()
     where document.document_id = trim(p_document_id)
       and document.company_id = v_company_id
       and document.deleted_at is null
       and exists (
           select 1
           from accounting.upload_source_master upload_source
           where upload_source.upload_source_id = document.upload_source_id
             and upload_source.default_department_id = p_department_id
       )
       and not exists (
           select 1
           from accounting.document_journal_links link
           where link.document_id = document.document_id
       )
    returning document.document_id;
end;
$$;

revoke all on function store.get_pending_receipts_internal(bigint, text)
    from public, anon, authenticated, service_role;
revoke all on function store.quick_enter_receipt_internal(bigint, text, date, numeric, text, text, text, jsonb, text, bigint, bigint)
    from public, anon, authenticated, service_role;
revoke all on function store.mark_receipt_scan_mistake_internal(bigint, text, text)
    from public, anon, authenticated, service_role;

commit;
