-- 店舗別の標準セット・延長料金と、その計算モジュールです。
-- 自由数式や動的SQLは使わず、pricing_mode ごとに名前付き実装を追加します。

create table if not exists public.store_pricing_plan_master (
    pricing_plan_id bigint generated by default as identity primary key,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    pricing_mode text not null default 'set_extension_v1',
    plan_version integer not null default 1,
    set_minutes integer not null default 60,
    set_unit_price_single numeric(12, 0) not null default 0,
    set_unit_price_per_customer numeric(12, 0) not null default 0,
    extension_unit_price_single numeric(12, 0) not null default 0,
    extension_unit_price_per_customer numeric(12, 0) not null default 0,
    is_active boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_pricing_plan_mode check (pricing_mode ~ '^[a-z][a-z0-9_]{0,63}$'),
    constraint chk_store_pricing_plan_version check (plan_version >= 1),
    constraint chk_store_pricing_plan_set_minutes check (set_minutes between 5 and 480 and mod(set_minutes, 5) = 0),
    constraint chk_store_pricing_plan_set_single check (set_unit_price_single >= 0),
    constraint chk_store_pricing_plan_set_per_customer check (set_unit_price_per_customer >= 0),
    constraint chk_store_pricing_plan_extension_single check (extension_unit_price_single >= 0),
    constraint chk_store_pricing_plan_extension_per_customer check (extension_unit_price_per_customer >= 0)
);

create unique index if not exists ux_store_pricing_plan_master_active_department
    on public.store_pricing_plan_master(department_id)
    where is_active;

create table if not exists public.store_slip_pricing_lines (
    pricing_line_id bigint generated by default as identity primary key,
    slip_id bigint not null references public.store_slips(slip_id) on delete cascade,
    business_day_id bigint references public.store_business_days(business_day_id),
    business_date date,
    company_id bigint not null references public.company_master(company_id),
    department_id bigint not null references public.department_master(department_id),
    pricing_plan_id bigint references public.store_pricing_plan_master(pricing_plan_id),
    pricing_plan_version integer not null,
    pricing_mode text not null,
    line_no integer not null,
    pricing_code text not null,
    line_name text not null,
    occurred_at timestamp with time zone not null,
    customer_count integer not null,
    quantity integer not null,
    unit_price numeric(12, 0) not null,
    amount numeric(12, 0) not null,
    slip_cast_id bigint references public.store_slip_casts(slip_cast_id) on delete set null,
    status text not null default 'active',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint chk_store_slip_pricing_line_version check (pricing_plan_version >= 1),
    constraint chk_store_slip_pricing_line_mode check (pricing_mode ~ '^[a-z][a-z0-9_]{0,63}$'),
    constraint chk_store_slip_pricing_line_code check (pricing_code in ('set', 'extension')),
    constraint chk_store_slip_pricing_line_name check (length(trim(line_name)) > 0),
    constraint chk_store_slip_pricing_line_customer_count check (customer_count > 0),
    constraint chk_store_slip_pricing_line_quantity check (quantity > 0),
    constraint chk_store_slip_pricing_line_unit_price check (unit_price >= 0),
    constraint chk_store_slip_pricing_line_amount check (amount >= 0),
    constraint chk_store_slip_pricing_line_status check (status in ('active', 'voided', 'cancelled')),
    constraint uq_store_slip_pricing_line unique (slip_id, line_no)
);

create index if not exists idx_store_slip_pricing_lines_slip_status
    on public.store_slip_pricing_lines(slip_id, status, occurred_at);

create index if not exists idx_store_slip_pricing_lines_day
    on public.store_slip_pricing_lines(company_id, department_id, business_day_id, status);

create index if not exists idx_store_slip_pricing_lines_business_day
    on public.store_slip_pricing_lines(business_day_id);

create index if not exists idx_store_slip_pricing_lines_department
    on public.store_slip_pricing_lines(department_id, status);

create index if not exists idx_store_slip_pricing_lines_plan
    on public.store_slip_pricing_lines(pricing_plan_id);

create index if not exists idx_store_slip_pricing_lines_slip_cast
    on public.store_slip_pricing_lines(slip_cast_id);

alter table public.store_pricing_plan_master enable row level security;
alter table public.store_slip_pricing_lines enable row level security;

drop trigger if exists trg_store_pricing_plan_master_set_updated_at on public.store_pricing_plan_master;
create trigger trg_store_pricing_plan_master_set_updated_at
before update on public.store_pricing_plan_master
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_pricing_lines_set_updated_at on public.store_slip_pricing_lines;
create trigger trg_store_slip_pricing_lines_set_updated_at
before update on public.store_slip_pricing_lines
for each row execute function public.set_updated_at();

drop trigger if exists trg_store_slip_pricing_lines_business_ui_revision on public.store_slip_pricing_lines;
create trigger trg_store_slip_pricing_lines_business_ui_revision
after insert or update or delete on public.store_slip_pricing_lines
for each row execute function public.bump_store_business_day_ui_revision_from_slip();

drop function if exists store.calculate_slip_pricing(bigint, bigint, timestamp with time zone);

create or replace function store.calculate_slip_pricing(
    p_department_id bigint,
    p_slip_id bigint,
    p_as_of timestamp with time zone
)
returns table (
    pricing_plan_id bigint,
    pricing_plan_version integer,
    pricing_mode text,
    pricing_code text,
    line_name text,
    occurred_at timestamp with time zone,
    customer_count integer,
    quantity integer,
    unit_price numeric,
    amount numeric,
    slip_cast_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_slip public.store_slips%rowtype;
    v_plan public.store_pricing_plan_master%rowtype;
    v_extension_count integer;
begin
    if p_as_of is null then
        raise exception 'invalid_pricing_as_of';
    end if;

    select s.*
      into v_slip
      from public.store_slips s
     where s.department_id = p_department_id
       and s.slip_id = p_slip_id;

    if v_slip.slip_id is null then
        raise exception 'store_slip_not_found';
    end if;

    if p_as_of < v_slip.opened_at then
        return;
    end if;

    select p.*
      into v_plan
      from public.store_pricing_plan_master p
     where p.department_id = p_department_id
       and p.company_id = v_slip.company_id
       and p.is_active = true
     order by p.updated_at desc, p.pricing_plan_id desc
     limit 1;

    -- 料金未設定の店舗は既存運用を変えず、自動料金を発生させません。
    if v_plan.pricing_plan_id is null then
        return;
    end if;

    if v_plan.pricing_mode <> 'set_extension_v1' then
        raise exception 'unsupported_pricing_mode';
    end if;

    v_extension_count := floor(extract(epoch from (p_as_of - v_slip.opened_at)) / (v_plan.set_minutes * 60))::integer;

    return query
    with events as (
        select 0::integer as event_no, 'set'::text as pricing_code, v_slip.opened_at as occurred_at
        union all
        select n, 'extension'::text, v_slip.opened_at + (n * v_plan.set_minutes) * interval '1 minute'
        from generate_series(1, greatest(v_extension_count, 0)) as n
    ), counts as (
        select
            e.event_no,
            e.pricing_code,
            e.occurred_at,
            count(c.slip_customer_id)::integer as customer_count
        from events e
        left join public.store_slip_customers c
          on c.slip_id = v_slip.slip_id
         and c.status <> 'cancelled'
         and c.entered_at <= e.occurred_at
         and (c.left_at is null or c.left_at > e.occurred_at)
        group by e.event_no, e.pricing_code, e.occurred_at
    ), priced as (
        select
            c.*,
            case when c.customer_count = 1 then 1 else c.customer_count end as quantity,
            case
                when c.pricing_code = 'set' and c.customer_count = 1 then v_plan.set_unit_price_single
                when c.pricing_code = 'set' then v_plan.set_unit_price_per_customer
                when c.customer_count = 1 then v_plan.extension_unit_price_single
                else v_plan.extension_unit_price_per_customer
            end as unit_price
        from counts c
        where c.customer_count > 0
    )
    select
        v_plan.pricing_plan_id,
        v_plan.plan_version,
        v_plan.pricing_mode,
        p.pricing_code,
        case p.pricing_code when 'set' then 'セット料金' else '延長料金' end,
        p.occurred_at,
        p.customer_count,
        p.quantity,
        p.unit_price,
        p.quantity * p.unit_price,
        null::bigint
    from priced p
    order by p.event_no;
end;
$$;

drop function if exists store.get_pricing_plan(bigint);

create or replace function store.get_pricing_plan(p_department_id bigint)
returns table (
    pricing_mode text,
    plan_version integer,
    set_minutes integer,
    set_unit_price_single numeric,
    set_unit_price_per_customer numeric,
    extension_unit_price_single numeric,
    extension_unit_price_per_customer numeric,
    is_active boolean
)
language sql
security definer
set search_path = public
as $$
    select
        coalesce(p.pricing_mode, 'set_extension_v1'),
        coalesce(p.plan_version, 1),
        coalesce(p.set_minutes, 60),
        coalesce(p.set_unit_price_single, 0),
        coalesce(p.set_unit_price_per_customer, 0),
        coalesce(p.extension_unit_price_single, 0),
        coalesce(p.extension_unit_price_per_customer, 0),
        coalesce(p.is_active, false)
    from (select 1) seed
    left join lateral (
        select p.*
        from public.store_pricing_plan_master p
        join public.department_master d
          on d.department_id = p.department_id
         and d.company_id = p.company_id
         and d.is_active = true
        where p.department_id = p_department_id
        order by p.is_active desc, p.updated_at desc, p.pricing_plan_id desc
        limit 1
    ) p on true
    where exists (
        select 1
        from public.department_master d
        where d.department_id = p_department_id
          and d.is_active = true
    );
$$;

drop function if exists store.save_pricing_plan(bigint, integer, numeric, numeric, numeric, numeric, boolean);

create or replace function store.save_pricing_plan(
    p_department_id bigint,
    p_set_minutes integer,
    p_set_unit_price_single numeric,
    p_set_unit_price_per_customer numeric,
    p_extension_unit_price_single numeric,
    p_extension_unit_price_per_customer numeric,
    p_is_active boolean
)
returns table (plan_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_company_id bigint;
    v_plan public.store_pricing_plan_master%rowtype;
    v_changed boolean;
begin
    select d.company_id
      into v_company_id
      from public.department_master d
     where d.department_id = p_department_id
       and d.is_active = true;

    if v_company_id is null or
       p_set_minutes is null or p_set_minutes < 5 or p_set_minutes > 480 or mod(p_set_minutes, 5) <> 0 or
       coalesce(p_set_unit_price_single, -1) < 0 or
       coalesce(p_set_unit_price_per_customer, -1) < 0 or
       coalesce(p_extension_unit_price_single, -1) < 0 or
       coalesce(p_extension_unit_price_per_customer, -1) < 0 or
       p_set_unit_price_single <> trunc(p_set_unit_price_single) or
       p_set_unit_price_per_customer <> trunc(p_set_unit_price_per_customer) or
       p_extension_unit_price_single <> trunc(p_extension_unit_price_single) or
       p_extension_unit_price_per_customer <> trunc(p_extension_unit_price_per_customer) or
       greatest(p_set_unit_price_single, p_set_unit_price_per_customer, p_extension_unit_price_single, p_extension_unit_price_per_customer) > 99999999 then
        raise exception 'invalid_pricing_plan';
    end if;

    select p.*
      into v_plan
      from public.store_pricing_plan_master p
     where p.department_id = p_department_id
     order by p.is_active desc, p.updated_at desc, p.pricing_plan_id desc
     limit 1
     for update;

    if v_plan.pricing_plan_id is null then
        insert into public.store_pricing_plan_master (
            company_id, department_id, pricing_mode, plan_version,
            set_minutes, set_unit_price_single, set_unit_price_per_customer,
            extension_unit_price_single, extension_unit_price_per_customer, is_active
        ) values (
            v_company_id, p_department_id, 'set_extension_v1', 1,
            p_set_minutes, p_set_unit_price_single, p_set_unit_price_per_customer,
            p_extension_unit_price_single, p_extension_unit_price_per_customer, p_is_active
        ) returning * into v_plan;
    else
        v_changed := v_plan.set_minutes is distinct from p_set_minutes or
            v_plan.set_unit_price_single is distinct from p_set_unit_price_single or
            v_plan.set_unit_price_per_customer is distinct from p_set_unit_price_per_customer or
            v_plan.extension_unit_price_single is distinct from p_extension_unit_price_single or
            v_plan.extension_unit_price_per_customer is distinct from p_extension_unit_price_per_customer;

        update public.store_pricing_plan_master p
           set company_id = v_company_id,
               pricing_mode = 'set_extension_v1',
               plan_version = case when v_changed then p.plan_version + 1 else p.plan_version end,
               set_minutes = p_set_minutes,
               set_unit_price_single = p_set_unit_price_single,
               set_unit_price_per_customer = p_set_unit_price_per_customer,
               extension_unit_price_single = p_extension_unit_price_single,
               extension_unit_price_per_customer = p_extension_unit_price_per_customer,
               is_active = p_is_active,
               updated_at = now()
         where p.pricing_plan_id = v_plan.pricing_plan_id
         returning * into v_plan;
    end if;

    if p_is_active then
        update public.store_pricing_plan_master p
           set is_active = false,
               updated_at = now()
         where p.department_id = p_department_id
           and p.pricing_plan_id <> v_plan.pricing_plan_id
           and p.is_active;
    end if;

    return query select v_plan.plan_version;
end;
$$;

revoke execute on function store.calculate_slip_pricing(bigint, bigint, timestamp with time zone) from public, anon, authenticated, service_role;
