grant execute on function public.get_store_context(bigint) to anon, authenticated, service_role;
grant execute on function public.get_current_business_day(bigint) to anon, authenticated, service_role;
grant execute on function public.get_open_slip_count(bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.get_store_tables(bigint) to anon, authenticated, service_role;
grant execute on function public.get_store_casts(bigint) to anon, authenticated, service_role;
grant execute on function public.get_store_cast_admin_list(bigint) to anon, authenticated, service_role;
grant execute on function public.get_business_day_slips(bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.get_order_entry_slips(bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.get_store_order_items(bigint) to anon, authenticated, service_role;
grant execute on function public.get_store_item_admin_catalog(bigint) to anon, authenticated, service_role;
grant execute on function public.get_order_attending_casts(bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.get_store_slip_detail(bigint, bigint) to anon, authenticated, service_role;
grant execute on function public.get_pending_receipts(bigint, text) to anon, authenticated, service_role;

revoke execute on function public.open_business_day(bigint, date, text) from public, anon;
revoke execute on function public.open_business_day_with_attendance(bigint, date, bigint[], text) from public, anon;
revoke execute on function public.open_business_day_with_attendance(bigint, date, jsonb, text) from public, anon;
revoke execute on function public.add_business_day_attendance(bigint, bigint, jsonb) from public, anon;
revoke execute on function public.save_business_day_attendance(bigint, bigint, jsonb) from public, anon;
revoke execute on function public.close_business_day(bigint, bigint, text) from public, anon;
revoke execute on function public.create_store_cast(bigint, text) from public, anon;
revoke execute on function public.delete_store_cast(bigint, bigint) from public, anon;
revoke execute on function public.upsert_store_item_category(bigint, bigint, text, text, integer, boolean) from public, anon;
revoke execute on function public.upsert_store_item(bigint, bigint, bigint, text, numeric, boolean, boolean, numeric, numeric, text) from public, anon;
revoke execute on function public.delete_store_item(bigint, bigint) from public, anon;
revoke execute on function public.reorder_store_items(bigint, jsonb) from public, anon;
revoke execute on function public.add_store_order_lines(bigint, bigint, jsonb) from public, anon;
revoke execute on function public.add_store_slip_customers(bigint, bigint, text[], timestamp with time zone) from public, anon;
revoke execute on function public.add_store_slip_nominations(bigint, bigint, jsonb) from public, anon;
revoke execute on function public.leave_store_slip_customer(bigint, bigint, timestamp with time zone) from public, anon;
revoke execute on function public.update_store_slip_customer_label(bigint, bigint, text) from public, anon;
revoke execute on function public.void_store_order_line(bigint, bigint) from public, anon;
revoke execute on function public.confirm_store_checkout(bigint, bigint, timestamp with time zone, jsonb, numeric) from public, anon;
revoke execute on function public.create_store_slip(bigint, bigint, timestamp with time zone, text[], jsonb, text) from public, anon;
revoke execute on function public.quick_enter_receipt(bigint, text, date, numeric, text, text, text, text) from public, anon;
revoke execute on function public.mark_receipt_scan_mistake(bigint, text, text) from public, anon;

grant execute on function public.open_business_day(bigint, date, text) to authenticated, service_role;
grant execute on function public.open_business_day_with_attendance(bigint, date, bigint[], text) to authenticated, service_role;
grant execute on function public.open_business_day_with_attendance(bigint, date, jsonb, text) to authenticated, service_role;
grant execute on function public.add_business_day_attendance(bigint, bigint, jsonb) to authenticated, service_role;
grant execute on function public.save_business_day_attendance(bigint, bigint, jsonb) to authenticated, service_role;
grant execute on function public.close_business_day(bigint, bigint, text) to authenticated, service_role;
grant execute on function public.create_store_cast(bigint, text) to authenticated, service_role;
grant execute on function public.delete_store_cast(bigint, bigint) to authenticated, service_role;
grant execute on function public.upsert_store_item_category(bigint, bigint, text, text, integer, boolean) to authenticated, service_role;
grant execute on function public.upsert_store_item(bigint, bigint, bigint, text, numeric, boolean, boolean, numeric, numeric, text) to authenticated, service_role;
grant execute on function public.delete_store_item(bigint, bigint) to authenticated, service_role;
grant execute on function public.reorder_store_items(bigint, jsonb) to authenticated, service_role;
grant execute on function public.add_store_order_lines(bigint, bigint, jsonb) to authenticated, service_role;
grant execute on function public.add_store_slip_customers(bigint, bigint, text[], timestamp with time zone) to authenticated, service_role;
grant execute on function public.add_store_slip_nominations(bigint, bigint, jsonb) to authenticated, service_role;
grant execute on function public.leave_store_slip_customer(bigint, bigint, timestamp with time zone) to authenticated, service_role;
grant execute on function public.update_store_slip_customer_label(bigint, bigint, text) to authenticated, service_role;
grant execute on function public.void_store_order_line(bigint, bigint) to authenticated, service_role;
grant execute on function public.confirm_store_checkout(bigint, bigint, timestamp with time zone, jsonb, numeric) to authenticated, service_role;
grant execute on function public.create_store_slip(bigint, bigint, timestamp with time zone, text[], jsonb, text) to authenticated, service_role;
grant execute on function public.quick_enter_receipt(bigint, text, date, numeric, text, text, text, text) to authenticated, service_role;
grant execute on function public.mark_receipt_scan_mistake(bigint, text, text) to authenticated, service_role;

commit;
